// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;

namespace DiGi_GIS_ML
{
    public partial class OrtoBuildingDetectionModel
    {
        /// <summary>
        /// model input class for OrtoBuildingDetectionModel.
        /// </summary>

        #region model input class

        public class ModelInput
        {
            /// <summary>
            /// Gets or sets the Reference.
            /// </summary>
            [LoadColumn(0)]
            [ColumnName(@"Reference")]
            public string Reference { get; set; } = string.Empty;

            /// <summary>
            /// Gets or sets the Building General Function.
            /// </summary>
            [LoadColumn(1)]
            [ColumnName(@"Building General Function")]
            public float Building_General_Function { get; set; }
            /// <summary>
            /// Gets or sets the Building Phase.
            /// </summary>

            [LoadColumn(2)]
            [ColumnName(@"Building Phase")]
            public float Building_Phase { get; set; }
            /// <summary>
            /// Gets or sets the number of storeys.
            /// </summary>

            [LoadColumn(3)]
            [ColumnName(@"Storeys")]
            public float Storeys { get; set; }
            /// <summary>
            /// Gets or sets the area.
            /// </summary>

            [LoadColumn(4)]
            [ColumnName(@"Area")]
            public float Area { get; set; }
            /// <summary>
            /// Gets or sets the location X-coordinate.
            /// </summary>

            [LoadColumn(5)]
            [ColumnName(@"Location X")]
            public float Location_X { get; set; }
            /// <summary>
            /// Gets or sets the location Y-coordinate.
            /// </summary>

            [LoadColumn(6)]
            [ColumnName(@"Location Y")]
            public float Location_Y { get; set; }
            /// <summary>
            /// Gets or sets the Voivodeship.
            /// </summary>

            [LoadColumn(7)]
            [ColumnName(@"Voivodeship")]
            public float Voivodeship { get; set; }
            /// <summary>
            /// Gets or sets the County.
            /// </summary>

            [LoadColumn(8)]
            [ColumnName(@"County")]
            public float County { get; set; }
            /// <summary>
            /// Gets or sets the Municipality.
            /// </summary>

            [LoadColumn(9)]
            [ColumnName(@"Municipality")]
            public float Municipality { get; set; }
            /// <summary>
            /// Gets or sets the Subdivision.
            /// </summary>

            [LoadColumn(10)]
            [ColumnName(@"Subdivision")]
            public float Subdivision { get; set; }
            /// <summary>
            /// Gets or sets the Subdivision Calculated Occupancy.
            /// </summary>

            [LoadColumn(11)]
            [ColumnName(@"Subdivision Calculated Occupancy")]
            public float Subdivision_Calculated_Occupancy { get; set; }
            /// <summary>
            /// Gets or sets the Subdivision Calculated Occupancy Area.
            /// </summary>

            [LoadColumn(12)]
            [ColumnName(@"Subdivision Calculated Occupancy Area")]
            public float Subdivision_Calculated_Occupancy_Area { get; set; }
            /// <summary>
            /// Gets or sets the BoundingBox X.
            /// </summary>

            [LoadColumn(13)]
            [ColumnName(@"BoundingBox X")]
            public float BoundingBox_X { get; set; }
            /// <summary>
            /// Gets or sets the BoundingBox Y.
            /// </summary>

            [LoadColumn(14)]
            [ColumnName(@"BoundingBox Y")]
            public float BoundingBox_Y { get; set; }
            /// <summary>
            /// Gets or sets the BoundingBox Width.
            /// </summary>

            [LoadColumn(15)]
            [ColumnName(@"BoundingBox Width")]
            public float BoundingBox_Width { get; set; }
            /// <summary>
            /// Gets or sets the BoundingBox Height.
            /// </summary>

            [LoadColumn(16)]
            [ColumnName(@"BoundingBox Height")]
            public float BoundingBox_Height { get; set; }
            /// <summary>
            /// Gets or sets the population value for the year 2008.
            /// </summary>

            [LoadColumn(17)]
            [ColumnName(@"Polpulation 2008")]
            public float Polpulation_2008 { get; set; }
            /// <summary>
            /// Gets or sets the population value for the year 2009.
            /// </summary>

            [LoadColumn(18)]
            [ColumnName(@"Polpulation 2009")]
            public float Polpulation_2009 { get; set; }
            /// <summary>
            /// Gets or sets the population value for the year 2010.
            /// </summary>

            [LoadColumn(19)]
            [ColumnName(@"Polpulation 2010")]
            public float Polpulation_2010 { get; set; }
            /// <summary>
            /// Gets or sets the population value for the year 2011.
            /// </summary>

            [LoadColumn(20)]
            [ColumnName(@"Polpulation 2011")]
            public float Polpulation_2011 { get; set; }
            /// <summary>
            /// Gets or sets the population value for the year 2012.
            /// </summary>

            [LoadColumn(21)]
            [ColumnName(@"Polpulation 2012")]
            public float Polpulation_2012 { get; set; }
            /// <summary>
            /// Gets or sets the population value for the year 2013.
            /// </summary>

            [LoadColumn(22)]
            [ColumnName(@"Polpulation 2013")]
            public float Polpulation_2013 { get; set; }
            /// <summary>
            /// Gets or sets the population value for the year 2014.
            /// </summary>

            [LoadColumn(23)]
            [ColumnName(@"Polpulation 2014")]
            public float Polpulation_2014 { get; set; }
            /// <summary>
            /// Gets or sets the population value for the year 2015.
            /// </summary>

            [LoadColumn(24)]
            [ColumnName(@"Polpulation 2015")]
            public float Polpulation_2015 { get; set; }
            /// <summary>
            /// Gets or sets the population value for the year 2016.
            /// </summary>

            [LoadColumn(25)]
            [ColumnName(@"Polpulation 2016")]
            public float Polpulation_2016 { get; set; }
            /// <summary>
            /// Gets or sets the population value for the year 2017.
            /// </summary>

            [LoadColumn(26)]
            [ColumnName(@"Polpulation 2017")]
            public float Polpulation_2017 { get; set; }
            /// <summary>
            /// Gets or sets the population value for the year 2018.
            /// </summary>

            [LoadColumn(27)]
            [ColumnName(@"Polpulation 2018")]
            public float Polpulation_2018 { get; set; }
            /// <summary>
            /// Gets or sets the population value for the year 2019.
            /// </summary>

            [LoadColumn(28)]
            [ColumnName(@"Polpulation 2019")]
            public float Polpulation_2019 { get; set; }
            /// <summary>
            /// Gets or sets the population value for the year 2020.
            /// </summary>

            [LoadColumn(29)]
            [ColumnName(@"Polpulation 2020")]
            public float Polpulation_2020 { get; set; }
            /// <summary>
            /// Gets or sets the population value for the year 2021.
            /// </summary>

            [LoadColumn(30)]
            [ColumnName(@"Polpulation 2021")]
            public float Polpulation_2021 { get; set; }
            /// <summary>
            /// Gets or sets the population value for the year 2022.
            /// </summary>

            [LoadColumn(31)]
            [ColumnName(@"Polpulation 2022")]
            public float Polpulation_2022 { get; set; }
            /// <summary>
            /// Gets or sets the population value for the year 2023.
            /// </summary>

            [LoadColumn(32)]
            [ColumnName(@"Polpulation 2023")]
            public float Polpulation_2023 { get; set; }
            /// <summary>
            /// Gets or sets the population value for the year 2024.
            /// </summary>

            [LoadColumn(33)]
            [ColumnName(@"Polpulation 2024")]
            public float Polpulation_2024 { get; set; }
            /// <summary>
            /// Gets or sets the population value for the year 2025.
            /// </summary>

            [LoadColumn(34)]
            [ColumnName(@"Polpulation 2025")]
            public float Polpulation_2025 { get; set; }
            /// <summary>
            /// Gets or sets the prediction confidence value for the year 2008.
            /// </summary>

            [LoadColumn(35)]
            [ColumnName(@"Prediction Confidence 2008")]
            public float Prediction_Confidence_2008 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box X-coordinate for the year 2008.
            /// </summary>

            [LoadColumn(36)]
            [ColumnName(@"Prediction BoundingBox X 2008")]
            public float Prediction_BoundingBox_X_2008 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box Y-coordinate for the year 2008.
            /// </summary>

            [LoadColumn(37)]
            [ColumnName(@"Prediction BoundingBox Y 2008")]
            public float Prediction_BoundingBox_Y_2008 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box width for the year 2008.
            /// </summary>

            [LoadColumn(38)]
            [ColumnName(@"Prediction BoundingBox Width 2008")]
            public float Prediction_BoundingBox_Width_2008 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box height for the year 2008.
            /// </summary>

            [LoadColumn(39)]
            [ColumnName(@"Prediction BoundingBox Height 2008")]
            public float Prediction_BoundingBox_Height_2008 { get; set; }
            /// <summary>
            /// Gets or sets the prediction confidence value for the year 2009.
            /// </summary>

            [LoadColumn(40)]
            [ColumnName(@"Prediction Confidence 2009")]
            public float Prediction_Confidence_2009 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box X-coordinate for the year 2009.
            /// </summary>

            [LoadColumn(41)]
            [ColumnName(@"Prediction BoundingBox X 2009")]
            public float Prediction_BoundingBox_X_2009 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box Y-coordinate for the year 2009.
            /// </summary>

            [LoadColumn(42)]
            [ColumnName(@"Prediction BoundingBox Y 2009")]
            public float Prediction_BoundingBox_Y_2009 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box width for the year 2009.
            /// </summary>

            [LoadColumn(43)]
            [ColumnName(@"Prediction BoundingBox Width 2009")]
            public float Prediction_BoundingBox_Width_2009 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box height for the year 2009.
            /// </summary>

            [LoadColumn(44)]
            [ColumnName(@"Prediction BoundingBox Height 2009")]
            public float Prediction_BoundingBox_Height_2009 { get; set; }
            /// <summary>
            /// Gets or sets the prediction confidence value for the year 2010.
            /// </summary>

            [LoadColumn(45)]
            [ColumnName(@"Prediction Confidence 2010")]
            public float Prediction_Confidence_2010 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box X-coordinate for the year 2010.
            /// </summary>

            [LoadColumn(46)]
            [ColumnName(@"Prediction BoundingBox X 2010")]
            public float Prediction_BoundingBox_X_2010 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box Y-coordinate for the year 2010.
            /// </summary>

            [LoadColumn(47)]
            [ColumnName(@"Prediction BoundingBox Y 2010")]
            public float Prediction_BoundingBox_Y_2010 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box width for the year 2010.
            /// </summary>

            [LoadColumn(48)]
            [ColumnName(@"Prediction BoundingBox Width 2010")]
            public float Prediction_BoundingBox_Width_2010 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box height for the year 2010.
            /// </summary>

            [LoadColumn(49)]
            [ColumnName(@"Prediction BoundingBox Height 2010")]
            public float Prediction_BoundingBox_Height_2010 { get; set; }
            /// <summary>
            /// Gets or sets the prediction confidence value for the year 2011.
            /// </summary>

            [LoadColumn(50)]
            [ColumnName(@"Prediction Confidence 2011")]
            public float Prediction_Confidence_2011 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box X-coordinate for the year 2011.
            /// </summary>

            [LoadColumn(51)]
            [ColumnName(@"Prediction BoundingBox X 2011")]
            public float Prediction_BoundingBox_X_2011 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box Y-coordinate for the year 2011.
            /// </summary>

            [LoadColumn(52)]
            [ColumnName(@"Prediction BoundingBox Y 2011")]
            public float Prediction_BoundingBox_Y_2011 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box width for the year 2011.
            /// </summary>

            [LoadColumn(53)]
            [ColumnName(@"Prediction BoundingBox Width 2011")]
            public float Prediction_BoundingBox_Width_2011 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box height for the year 2011.
            /// </summary>

            [LoadColumn(54)]
            [ColumnName(@"Prediction BoundingBox Height 2011")]
            public float Prediction_BoundingBox_Height_2011 { get; set; }
            /// <summary>
            /// Gets or sets the prediction confidence value for the year 2012.
            /// </summary>

            [LoadColumn(55)]
            [ColumnName(@"Prediction Confidence 2012")]
            public float Prediction_Confidence_2012 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box X-coordinate for the year 2012.
            /// </summary>

            [LoadColumn(56)]
            [ColumnName(@"Prediction BoundingBox X 2012")]
            public float Prediction_BoundingBox_X_2012 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box Y-coordinate for the year 2012.
            /// </summary>

            [LoadColumn(57)]
            [ColumnName(@"Prediction BoundingBox Y 2012")]
            public float Prediction_BoundingBox_Y_2012 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box width for the year 2012.
            /// </summary>

            [LoadColumn(58)]
            [ColumnName(@"Prediction BoundingBox Width 2012")]
            public float Prediction_BoundingBox_Width_2012 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box height for the year 2012.
            /// </summary>

            [LoadColumn(59)]
            [ColumnName(@"Prediction BoundingBox Height 2012")]
            public float Prediction_BoundingBox_Height_2012 { get; set; }
            /// <summary>
            /// Gets or sets the prediction confidence value for the year 2013.
            /// </summary>

            [LoadColumn(60)]
            [ColumnName(@"Prediction Confidence 2013")]
            public float Prediction_Confidence_2013 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box X-coordinate for the year 2013.
            /// </summary>

            [LoadColumn(61)]
            [ColumnName(@"Prediction BoundingBox X 2013")]
            public float Prediction_BoundingBox_X_2013 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box Y-coordinate for the year 2013.
            /// </summary>

            [LoadColumn(62)]
            [ColumnName(@"Prediction BoundingBox Y 2013")]
            public float Prediction_BoundingBox_Y_2013 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box width for the year 2013.
            /// </summary>

            [LoadColumn(63)]
            [ColumnName(@"Prediction BoundingBox Width 2013")]
            public float Prediction_BoundingBox_Width_2013 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box height for the year 2013.
            /// </summary>

            [LoadColumn(64)]
            [ColumnName(@"Prediction BoundingBox Height 2013")]
            public float Prediction_BoundingBox_Height_2013 { get; set; }
            /// <summary>
            /// Gets or sets the prediction confidence value for the year 2014.
            /// </summary>

            [LoadColumn(65)]
            [ColumnName(@"Prediction Confidence 2014")]
            public float Prediction_Confidence_2014 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box X-coordinate for the year 2014.
            /// </summary>

            [LoadColumn(66)]
            [ColumnName(@"Prediction BoundingBox X 2014")]
            public float Prediction_BoundingBox_X_2014 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box Y-coordinate for the year 2014.
            /// </summary>

            [LoadColumn(67)]
            [ColumnName(@"Prediction BoundingBox Y 2014")]
            public float Prediction_BoundingBox_Y_2014 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box width for the year 2014.
            /// </summary>

            [LoadColumn(68)]
            [ColumnName(@"Prediction BoundingBox Width 2014")]
            public float Prediction_BoundingBox_Width_2014 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box height for the year 2014.
            /// </summary>

            [LoadColumn(69)]
            [ColumnName(@"Prediction BoundingBox Height 2014")]
            public float Prediction_BoundingBox_Height_2014 { get; set; }
            /// <summary>
            /// Gets or sets the prediction confidence value for the year 2015.
            /// </summary>

            [LoadColumn(70)]
            [ColumnName(@"Prediction Confidence 2015")]
            public float Prediction_Confidence_2015 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box X-coordinate for the year 2015.
            /// </summary>

            [LoadColumn(71)]
            [ColumnName(@"Prediction BoundingBox X 2015")]
            public float Prediction_BoundingBox_X_2015 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box Y-coordinate for the year 2015.
            /// </summary>

            [LoadColumn(72)]
            [ColumnName(@"Prediction BoundingBox Y 2015")]
            public float Prediction_BoundingBox_Y_2015 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box width for the year 2015.
            /// </summary>

            [LoadColumn(73)]
            [ColumnName(@"Prediction BoundingBox Width 2015")]
            public float Prediction_BoundingBox_Width_2015 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box height for the year 2015.
            /// </summary>

            [LoadColumn(74)]
            [ColumnName(@"Prediction BoundingBox Height 2015")]
            public float Prediction_BoundingBox_Height_2015 { get; set; }
            /// <summary>
            /// Gets or sets the prediction confidence value for the year 2016.
            /// </summary>

            [LoadColumn(75)]
            [ColumnName(@"Prediction Confidence 2016")]
            public float Prediction_Confidence_2016 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box X-coordinate for the year 2016.
            /// </summary>

            [LoadColumn(76)]
            [ColumnName(@"Prediction BoundingBox X 2016")]
            public float Prediction_BoundingBox_X_2016 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box Y-coordinate for the year 2016.
            /// </summary>

            [LoadColumn(77)]
            [ColumnName(@"Prediction BoundingBox Y 2016")]
            public float Prediction_BoundingBox_Y_2016 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box width for the year 2016.
            /// </summary>

            [LoadColumn(78)]
            [ColumnName(@"Prediction BoundingBox Width 2016")]
            public float Prediction_BoundingBox_Width_2016 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box height for the year 2016.
            /// </summary>

            [LoadColumn(79)]
            [ColumnName(@"Prediction BoundingBox Height 2016")]
            public float Prediction_BoundingBox_Height_2016 { get; set; }
            /// <summary>
            /// Gets or sets the prediction confidence value for the year 2017.
            /// </summary>

            [LoadColumn(80)]
            [ColumnName(@"Prediction Confidence 2017")]
            public float Prediction_Confidence_2017 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box X-coordinate for the year 2017.
            /// </summary>

            [LoadColumn(81)]
            [ColumnName(@"Prediction BoundingBox X 2017")]
            public float Prediction_BoundingBox_X_2017 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box Y-coordinate for the year 2017.
            /// </summary>

            [LoadColumn(82)]
            [ColumnName(@"Prediction BoundingBox Y 2017")]
            public float Prediction_BoundingBox_Y_2017 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box width for the year 2017.
            /// </summary>

            [LoadColumn(83)]
            [ColumnName(@"Prediction BoundingBox Width 2017")]
            public float Prediction_BoundingBox_Width_2017 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box height for the year 2017.
            /// </summary>

            [LoadColumn(84)]
            [ColumnName(@"Prediction BoundingBox Height 2017")]
            public float Prediction_BoundingBox_Height_2017 { get; set; }
            /// <summary>
            /// Gets or sets the prediction confidence value for the year 2018.
            /// </summary>

            [LoadColumn(85)]
            [ColumnName(@"Prediction Confidence 2018")]
            public float Prediction_Confidence_2018 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box X-coordinate for the year 2018.
            /// </summary>

            [LoadColumn(86)]
            [ColumnName(@"Prediction BoundingBox X 2018")]
            public float Prediction_BoundingBox_X_2018 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box Y-coordinate for the year 2018.
            /// </summary>

            [LoadColumn(87)]
            [ColumnName(@"Prediction BoundingBox Y 2018")]
            public float Prediction_BoundingBox_Y_2018 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box width for the year 2018.
            /// </summary>

            [LoadColumn(88)]
            [ColumnName(@"Prediction BoundingBox Width 2018")]
            public float Prediction_BoundingBox_Width_2018 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box height for the year 2018.
            /// </summary>

            [LoadColumn(89)]
            [ColumnName(@"Prediction BoundingBox Height 2018")]
            public float Prediction_BoundingBox_Height_2018 { get; set; }
            /// <summary>
            /// Gets or sets the prediction confidence value for the year 2019.
            /// </summary>

            [LoadColumn(90)]
            [ColumnName(@"Prediction Confidence 2019")]
            public float Prediction_Confidence_2019 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box X-coordinate for the year 2019.
            /// </summary>

            [LoadColumn(91)]
            [ColumnName(@"Prediction BoundingBox X 2019")]
            public float Prediction_BoundingBox_X_2019 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box Y-coordinate for the year 2019.
            /// </summary>

            [LoadColumn(92)]
            [ColumnName(@"Prediction BoundingBox Y 2019")]
            public float Prediction_BoundingBox_Y_2019 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box width for the year 2019.
            /// </summary>

            [LoadColumn(93)]
            [ColumnName(@"Prediction BoundingBox Width 2019")]
            public float Prediction_BoundingBox_Width_2019 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box height for the year 2019.
            /// </summary>

            [LoadColumn(94)]
            [ColumnName(@"Prediction BoundingBox Height 2019")]
            public float Prediction_BoundingBox_Height_2019 { get; set; }
            /// <summary>
            /// Gets or sets the prediction confidence value for the year 2020.
            /// </summary>

            [LoadColumn(95)]
            [ColumnName(@"Prediction Confidence 2020")]
            public float Prediction_Confidence_2020 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box X-coordinate for the year 2020.
            /// </summary>

            [LoadColumn(96)]
            [ColumnName(@"Prediction BoundingBox X 2020")]
            public float Prediction_BoundingBox_X_2020 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box Y-coordinate for the year 2020.
            /// </summary>

            [LoadColumn(97)]
            [ColumnName(@"Prediction BoundingBox Y 2020")]
            public float Prediction_BoundingBox_Y_2020 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box width for the year 2020.
            /// </summary>

            [LoadColumn(98)]
            [ColumnName(@"Prediction BoundingBox Width 2020")]
            public float Prediction_BoundingBox_Width_2020 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box height for the year 2020.
            /// </summary>

            [LoadColumn(99)]
            [ColumnName(@"Prediction BoundingBox Height 2020")]
            public float Prediction_BoundingBox_Height_2020 { get; set; }
            /// <summary>
            /// Gets or sets the prediction confidence value for the year 2021.
            /// </summary>

            [LoadColumn(100)]
            [ColumnName(@"Prediction Confidence 2021")]
            public float Prediction_Confidence_2021 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box X-coordinate for the year 2021.
            /// </summary>

            [LoadColumn(101)]
            [ColumnName(@"Prediction BoundingBox X 2021")]
            public float Prediction_BoundingBox_X_2021 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box Y-coordinate for the year 2021.
            /// </summary>

            [LoadColumn(102)]
            [ColumnName(@"Prediction BoundingBox Y 2021")]
            public float Prediction_BoundingBox_Y_2021 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box width for the year 2021.
            /// </summary>

            [LoadColumn(103)]
            [ColumnName(@"Prediction BoundingBox Width 2021")]
            public float Prediction_BoundingBox_Width_2021 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box height for the year 2021.
            /// </summary>

            [LoadColumn(104)]
            [ColumnName(@"Prediction BoundingBox Height 2021")]
            public float Prediction_BoundingBox_Height_2021 { get; set; }
            /// <summary>
            /// Gets or sets the prediction confidence value for the year 2022.
            /// </summary>

            [LoadColumn(105)]
            [ColumnName(@"Prediction Confidence 2022")]
            public float Prediction_Confidence_2022 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box X-coordinate for the year 2022.
            /// </summary>

            [LoadColumn(106)]
            [ColumnName(@"Prediction BoundingBox X 2022")]
            public float Prediction_BoundingBox_X_2022 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box Y-coordinate for the year 2022.
            /// </summary>

            [LoadColumn(107)]
            [ColumnName(@"Prediction BoundingBox Y 2022")]
            public float Prediction_BoundingBox_Y_2022 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box width for the year 2022.
            /// </summary>

            [LoadColumn(108)]
            [ColumnName(@"Prediction BoundingBox Width 2022")]
            public float Prediction_BoundingBox_Width_2022 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box height for the year 2022.
            /// </summary>

            [LoadColumn(109)]
            [ColumnName(@"Prediction BoundingBox Height 2022")]
            public float Prediction_BoundingBox_Height_2022 { get; set; }
            /// <summary>
            /// Gets or sets the prediction confidence value for the year 2023.
            /// </summary>

            [LoadColumn(110)]
            [ColumnName(@"Prediction Confidence 2023")]
            public float Prediction_Confidence_2023 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box X-coordinate for the year 2023.
            /// </summary>

            [LoadColumn(111)]
            [ColumnName(@"Prediction BoundingBox X 2023")]
            public float Prediction_BoundingBox_X_2023 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box Y-coordinate for the year 2023.
            /// </summary>

            [LoadColumn(112)]
            [ColumnName(@"Prediction BoundingBox Y 2023")]
            public float Prediction_BoundingBox_Y_2023 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box width for the year 2023.
            /// </summary>

            [LoadColumn(113)]
            [ColumnName(@"Prediction BoundingBox Width 2023")]
            public float Prediction_BoundingBox_Width_2023 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box height for the year 2023.
            /// </summary>

            [LoadColumn(114)]
            [ColumnName(@"Prediction BoundingBox Height 2023")]
            public float Prediction_BoundingBox_Height_2023 { get; set; }
            /// <summary>
            /// Gets or sets the prediction confidence value for the year 2024.
            /// </summary>

            [LoadColumn(115)]
            [ColumnName(@"Prediction Confidence 2024")]
            public float Prediction_Confidence_2024 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box X-coordinate for the year 2024.
            /// </summary>

            [LoadColumn(116)]
            [ColumnName(@"Prediction BoundingBox X 2024")]
            public float Prediction_BoundingBox_X_2024 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box Y-coordinate for the year 2024.
            /// </summary>

            [LoadColumn(117)]
            [ColumnName(@"Prediction BoundingBox Y 2024")]
            public float Prediction_BoundingBox_Y_2024 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box width for the year 2024.
            /// </summary>

            [LoadColumn(118)]
            [ColumnName(@"Prediction BoundingBox Width 2024")]
            public float Prediction_BoundingBox_Width_2024 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box height for the year 2024.
            /// </summary>

            [LoadColumn(119)]
            [ColumnName(@"Prediction BoundingBox Height 2024")]
            public float Prediction_BoundingBox_Height_2024 { get; set; }
            /// <summary>
            /// Gets or sets the prediction confidence value for the year 2025.
            /// </summary>

            [LoadColumn(120)]
            [ColumnName(@"Prediction Confidence 2025")]
            public float Prediction_Confidence_2025 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box X-coordinate for the year 2025.
            /// </summary>

            [LoadColumn(121)]
            [ColumnName(@"Prediction BoundingBox X 2025")]
            public float Prediction_BoundingBox_X_2025 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box Y-coordinate for the year 2025.
            /// </summary>

            [LoadColumn(122)]
            [ColumnName(@"Prediction BoundingBox Y 2025")]
            public float Prediction_BoundingBox_Y_2025 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box width for the year 2025.
            /// </summary>

            [LoadColumn(123)]
            [ColumnName(@"Prediction BoundingBox Width 2025")]
            public float Prediction_BoundingBox_Width_2025 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box height for the year 2025.
            /// </summary>

            [LoadColumn(124)]
            [ColumnName(@"Prediction BoundingBox Height 2025")]
            public float Prediction_BoundingBox_Height_2025 { get; set; }
            /// <summary>
            /// Gets or sets the year the building was built.
            /// </summary>

            [LoadColumn(125)]
            [ColumnName(@"Year Built")]
            public float Year_Built { get; set; }
        }

        #endregion model input class

        /// <summary>
        /// model output class for OrtoBuildingDetectionModel.
        /// </summary>

        #region model output class

        public class ModelOutput
        {
            /// <summary>
            /// Gets or sets the Building General Function.
            /// </summary>
            [ColumnName(@"Building General Function")]
            public float Building_General_Function { get; set; }
            /// <summary>
            /// Gets or sets the Building Phase.
            /// </summary>

            [ColumnName(@"Building Phase")]
            public float Building_Phase { get; set; }
            /// <summary>
            /// Gets or sets the number of storeys.
            /// </summary>

            [ColumnName(@"Storeys")]
            public float Storeys { get; set; }
            /// <summary>
            /// Gets or sets the area.
            /// </summary>

            [ColumnName(@"Area")]
            public float Area { get; set; }
            /// <summary>
            /// Gets or sets the location X-coordinate.
            /// </summary>

            [ColumnName(@"Location X")]
            public float Location_X { get; set; }
            /// <summary>
            /// Gets or sets the location Y-coordinate.
            /// </summary>

            [ColumnName(@"Location Y")]
            public float Location_Y { get; set; }
            /// <summary>
            /// Gets or sets the Voivodeship.
            /// </summary>

            [ColumnName(@"Voivodeship")]
            public float Voivodeship { get; set; }
            /// <summary>
            /// Gets or sets the County.
            /// </summary>

            [ColumnName(@"County")]
            public float County { get; set; }
            /// <summary>
            /// Gets or sets the Municipality.
            /// </summary>

            [ColumnName(@"Municipality")]
            public float Municipality { get; set; }
            /// <summary>
            /// Gets or sets the Subdivision.
            /// </summary>

            [ColumnName(@"Subdivision")]
            public float Subdivision { get; set; }
            /// <summary>
            /// Gets or sets the Subdivision Calculated Occupancy.
            /// </summary>

            [ColumnName(@"Subdivision Calculated Occupancy")]
            public float Subdivision_Calculated_Occupancy { get; set; }
            /// <summary>
            /// Gets or sets the Subdivision Calculated Occupancy Area.
            /// </summary>

            [ColumnName(@"Subdivision Calculated Occupancy Area")]
            public float Subdivision_Calculated_Occupancy_Area { get; set; }
            /// <summary>
            /// Gets or sets the BoundingBox X.
            /// </summary>

            [ColumnName(@"BoundingBox X")]
            public float BoundingBox_X { get; set; }
            /// <summary>
            /// Gets or sets the BoundingBox Y.
            /// </summary>

            [ColumnName(@"BoundingBox Y")]
            public float BoundingBox_Y { get; set; }
            /// <summary>
            /// Gets or sets the BoundingBox Width.
            /// </summary>

            [ColumnName(@"BoundingBox Width")]
            public float BoundingBox_Width { get; set; }
            /// <summary>
            /// Gets or sets the BoundingBox Height.
            /// </summary>

            [ColumnName(@"BoundingBox Height")]
            public float BoundingBox_Height { get; set; }
            /// <summary>
            /// Gets or sets the population value for the year 2008.
            /// </summary>

            [ColumnName(@"Polpulation 2008")]
            public float Polpulation_2008 { get; set; }
            /// <summary>
            /// Gets or sets the population value for the year 2009.
            /// </summary>

            [ColumnName(@"Polpulation 2009")]
            public float Polpulation_2009 { get; set; }
            /// <summary>
            /// Gets or sets the population value for the year 2010.
            /// </summary>

            [ColumnName(@"Polpulation 2010")]
            public float Polpulation_2010 { get; set; }
            /// <summary>
            /// Gets or sets the population value for the year 2011.
            /// </summary>

            [ColumnName(@"Polpulation 2011")]
            public float Polpulation_2011 { get; set; }
            /// <summary>
            /// Gets or sets the population value for the year 2012.
            /// </summary>

            [ColumnName(@"Polpulation 2012")]
            public float Polpulation_2012 { get; set; }
            /// <summary>
            /// Gets or sets the population value for the year 2013.
            /// </summary>

            [ColumnName(@"Polpulation 2013")]
            public float Polpulation_2013 { get; set; }
            /// <summary>
            /// Gets or sets the population value for the year 2014.
            /// </summary>

            [ColumnName(@"Polpulation 2014")]
            public float Polpulation_2014 { get; set; }
            /// <summary>
            /// Gets or sets the population value for the year 2015.
            /// </summary>

            [ColumnName(@"Polpulation 2015")]
            public float Polpulation_2015 { get; set; }
            /// <summary>
            /// Gets or sets the population value for the year 2016.
            /// </summary>

            [ColumnName(@"Polpulation 2016")]
            public float Polpulation_2016 { get; set; }
            /// <summary>
            /// Gets or sets the population value for the year 2017.
            /// </summary>

            [ColumnName(@"Polpulation 2017")]
            public float Polpulation_2017 { get; set; }
            /// <summary>
            /// Gets or sets the population value for the year 2018.
            /// </summary>

            [ColumnName(@"Polpulation 2018")]
            public float Polpulation_2018 { get; set; }
            /// <summary>
            /// Gets or sets the population value for the year 2019.
            /// </summary>

            [ColumnName(@"Polpulation 2019")]
            public float Polpulation_2019 { get; set; }
            /// <summary>
            /// Gets or sets the population value for the year 2020.
            /// </summary>

            [ColumnName(@"Polpulation 2020")]
            public float Polpulation_2020 { get; set; }
            /// <summary>
            /// Gets or sets the population value for the year 2021.
            /// </summary>

            [ColumnName(@"Polpulation 2021")]
            public float Polpulation_2021 { get; set; }
            /// <summary>
            /// Gets or sets the population value for the year 2022.
            /// </summary>

            [ColumnName(@"Polpulation 2022")]
            public float Polpulation_2022 { get; set; }
            /// <summary>
            /// Gets or sets the population value for the year 2023.
            /// </summary>

            [ColumnName(@"Polpulation 2023")]
            public float Polpulation_2023 { get; set; }
            /// <summary>
            /// Gets or sets the population value for the year 2024.
            /// </summary>

            [ColumnName(@"Polpulation 2024")]
            public float Polpulation_2024 { get; set; }
            /// <summary>
            /// Gets or sets the population value for the year 2025.
            /// </summary>

            [ColumnName(@"Polpulation 2025")]
            public float Polpulation_2025 { get; set; }
            /// <summary>
            /// Gets or sets the prediction confidence value for the year 2008.
            /// </summary>

            [ColumnName(@"Prediction Confidence 2008")]
            public float Prediction_Confidence_2008 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box X-coordinate for the year 2008.
            /// </summary>

            [ColumnName(@"Prediction BoundingBox X 2008")]
            public float Prediction_BoundingBox_X_2008 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box Y-coordinate for the year 2008.
            /// </summary>

            [ColumnName(@"Prediction BoundingBox Y 2008")]
            public float Prediction_BoundingBox_Y_2008 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box width for the year 2008.
            /// </summary>

            [ColumnName(@"Prediction BoundingBox Width 2008")]
            public float Prediction_BoundingBox_Width_2008 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box height for the year 2008.
            /// </summary>

            [ColumnName(@"Prediction BoundingBox Height 2008")]
            public float Prediction_BoundingBox_Height_2008 { get; set; }
            /// <summary>
            /// Gets or sets the prediction confidence value for the year 2009.
            /// </summary>

            [ColumnName(@"Prediction Confidence 2009")]
            public float Prediction_Confidence_2009 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box X-coordinate for the year 2009.
            /// </summary>

            [ColumnName(@"Prediction BoundingBox X 2009")]
            public float Prediction_BoundingBox_X_2009 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box Y-coordinate for the year 2009.
            /// </summary>

            [ColumnName(@"Prediction BoundingBox Y 2009")]
            public float Prediction_BoundingBox_Y_2009 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box width for the year 2009.
            /// </summary>

            [ColumnName(@"Prediction BoundingBox Width 2009")]
            public float Prediction_BoundingBox_Width_2009 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box height for the year 2009.
            /// </summary>

            [ColumnName(@"Prediction BoundingBox Height 2009")]
            public float Prediction_BoundingBox_Height_2009 { get; set; }
            /// <summary>
            /// Gets or sets the prediction confidence value for the year 2010.
            /// </summary>

            [ColumnName(@"Prediction Confidence 2010")]
            public float Prediction_Confidence_2010 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box X-coordinate for the year 2010.
            /// </summary>

            [ColumnName(@"Prediction BoundingBox X 2010")]
            public float Prediction_BoundingBox_X_2010 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box Y-coordinate for the year 2010.
            /// </summary>

            [ColumnName(@"Prediction BoundingBox Y 2010")]
            public float Prediction_BoundingBox_Y_2010 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box width for the year 2010.
            /// </summary>

            [ColumnName(@"Prediction BoundingBox Width 2010")]
            public float Prediction_BoundingBox_Width_2010 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box height for the year 2010.
            /// </summary>

            [ColumnName(@"Prediction BoundingBox Height 2010")]
            public float Prediction_BoundingBox_Height_2010 { get; set; }
            /// <summary>
            /// Gets or sets the prediction confidence value for the year 2011.
            /// </summary>

            [ColumnName(@"Prediction Confidence 2011")]
            public float Prediction_Confidence_2011 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box X-coordinate for the year 2011.
            /// </summary>

            [ColumnName(@"Prediction BoundingBox X 2011")]
            public float Prediction_BoundingBox_X_2011 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box Y-coordinate for the year 2011.
            /// </summary>

            [ColumnName(@"Prediction BoundingBox Y 2011")]
            public float Prediction_BoundingBox_Y_2011 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box width for the year 2011.
            /// </summary>

            [ColumnName(@"Prediction BoundingBox Width 2011")]
            public float Prediction_BoundingBox_Width_2011 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box height for the year 2011.
            /// </summary>

            [ColumnName(@"Prediction BoundingBox Height 2011")]
            public float Prediction_BoundingBox_Height_2011 { get; set; }
            /// <summary>
            /// Gets or sets the prediction confidence value for the year 2012.
            /// </summary>

            [ColumnName(@"Prediction Confidence 2012")]
            public float Prediction_Confidence_2012 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box X-coordinate for the year 2012.
            /// </summary>

            [ColumnName(@"Prediction BoundingBox X 2012")]
            public float Prediction_BoundingBox_X_2012 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box Y-coordinate for the year 2012.
            /// </summary>

            [ColumnName(@"Prediction BoundingBox Y 2012")]
            public float Prediction_BoundingBox_Y_2012 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box width for the year 2012.
            /// </summary>

            [ColumnName(@"Prediction BoundingBox Width 2012")]
            public float Prediction_BoundingBox_Width_2012 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box height for the year 2012.
            /// </summary>

            [ColumnName(@"Prediction BoundingBox Height 2012")]
            public float Prediction_BoundingBox_Height_2012 { get; set; }
            /// <summary>
            /// Gets or sets the prediction confidence value for the year 2013.
            /// </summary>

            [ColumnName(@"Prediction Confidence 2013")]
            public float Prediction_Confidence_2013 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box X-coordinate for the year 2013.
            /// </summary>

            [ColumnName(@"Prediction BoundingBox X 2013")]
            public float Prediction_BoundingBox_X_2013 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box Y-coordinate for the year 2013.
            /// </summary>

            [ColumnName(@"Prediction BoundingBox Y 2013")]
            public float Prediction_BoundingBox_Y_2013 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box width for the year 2013.
            /// </summary>

            [ColumnName(@"Prediction BoundingBox Width 2013")]
            public float Prediction_BoundingBox_Width_2013 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box height for the year 2013.
            /// </summary>

            [ColumnName(@"Prediction BoundingBox Height 2013")]
            public float Prediction_BoundingBox_Height_2013 { get; set; }
            /// <summary>
            /// Gets or sets the prediction confidence value for the year 2014.
            /// </summary>

            [ColumnName(@"Prediction Confidence 2014")]
            public float Prediction_Confidence_2014 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box X-coordinate for the year 2014.
            /// </summary>

            [ColumnName(@"Prediction BoundingBox X 2014")]
            public float Prediction_BoundingBox_X_2014 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box Y-coordinate for the year 2014.
            /// </summary>

            [ColumnName(@"Prediction BoundingBox Y 2014")]
            public float Prediction_BoundingBox_Y_2014 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box width for the year 2014.
            /// </summary>

            [ColumnName(@"Prediction BoundingBox Width 2014")]
            public float Prediction_BoundingBox_Width_2014 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box height for the year 2014.
            /// </summary>

            [ColumnName(@"Prediction BoundingBox Height 2014")]
            public float Prediction_BoundingBox_Height_2014 { get; set; }
            /// <summary>
            /// Gets or sets the prediction confidence value for the year 2015.
            /// </summary>

            [ColumnName(@"Prediction Confidence 2015")]
            public float Prediction_Confidence_2015 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box X-coordinate for the year 2015.
            /// </summary>

            [ColumnName(@"Prediction BoundingBox X 2015")]
            public float Prediction_BoundingBox_X_2015 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box Y-coordinate for the year 2015.
            /// </summary>

            [ColumnName(@"Prediction BoundingBox Y 2015")]
            public float Prediction_BoundingBox_Y_2015 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box width for the year 2015.
            /// </summary>

            [ColumnName(@"Prediction BoundingBox Width 2015")]
            public float Prediction_BoundingBox_Width_2015 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box height for the year 2015.
            /// </summary>

            [ColumnName(@"Prediction BoundingBox Height 2015")]
            public float Prediction_BoundingBox_Height_2015 { get; set; }
            /// <summary>
            /// Gets or sets the prediction confidence value for the year 2016.
            /// </summary>

            [ColumnName(@"Prediction Confidence 2016")]
            public float Prediction_Confidence_2016 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box X-coordinate for the year 2016.
            /// </summary>

            [ColumnName(@"Prediction BoundingBox X 2016")]
            public float Prediction_BoundingBox_X_2016 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box Y-coordinate for the year 2016.
            /// </summary>

            [ColumnName(@"Prediction BoundingBox Y 2016")]
            public float Prediction_BoundingBox_Y_2016 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box width for the year 2016.
            /// </summary>

            [ColumnName(@"Prediction BoundingBox Width 2016")]
            public float Prediction_BoundingBox_Width_2016 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box height for the year 2016.
            /// </summary>

            [ColumnName(@"Prediction BoundingBox Height 2016")]
            public float Prediction_BoundingBox_Height_2016 { get; set; }
            /// <summary>
            /// Gets or sets the prediction confidence value for the year 2017.
            /// </summary>

            [ColumnName(@"Prediction Confidence 2017")]
            public float Prediction_Confidence_2017 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box X-coordinate for the year 2017.
            /// </summary>

            [ColumnName(@"Prediction BoundingBox X 2017")]
            public float Prediction_BoundingBox_X_2017 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box Y-coordinate for the year 2017.
            /// </summary>

            [ColumnName(@"Prediction BoundingBox Y 2017")]
            public float Prediction_BoundingBox_Y_2017 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box width for the year 2017.
            /// </summary>

            [ColumnName(@"Prediction BoundingBox Width 2017")]
            public float Prediction_BoundingBox_Width_2017 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box height for the year 2017.
            /// </summary>

            [ColumnName(@"Prediction BoundingBox Height 2017")]
            public float Prediction_BoundingBox_Height_2017 { get; set; }
            /// <summary>
            /// Gets or sets the prediction confidence value for the year 2018.
            /// </summary>

            [ColumnName(@"Prediction Confidence 2018")]
            public float Prediction_Confidence_2018 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box X-coordinate for the year 2018.
            /// </summary>

            [ColumnName(@"Prediction BoundingBox X 2018")]
            public float Prediction_BoundingBox_X_2018 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box Y-coordinate for the year 2018.
            /// </summary>

            [ColumnName(@"Prediction BoundingBox Y 2018")]
            public float Prediction_BoundingBox_Y_2018 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box width for the year 2018.
            /// </summary>

            [ColumnName(@"Prediction BoundingBox Width 2018")]
            public float Prediction_BoundingBox_Width_2018 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box height for the year 2018.
            /// </summary>

            [ColumnName(@"Prediction BoundingBox Height 2018")]
            public float Prediction_BoundingBox_Height_2018 { get; set; }
            /// <summary>
            /// Gets or sets the prediction confidence value for the year 2019.
            /// </summary>

            [ColumnName(@"Prediction Confidence 2019")]
            public float Prediction_Confidence_2019 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box X-coordinate for the year 2019.
            /// </summary>

            [ColumnName(@"Prediction BoundingBox X 2019")]
            public float Prediction_BoundingBox_X_2019 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box Y-coordinate for the year 2019.
            /// </summary>

            [ColumnName(@"Prediction BoundingBox Y 2019")]
            public float Prediction_BoundingBox_Y_2019 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box width for the year 2019.
            /// </summary>

            [ColumnName(@"Prediction BoundingBox Width 2019")]
            public float Prediction_BoundingBox_Width_2019 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box height for the year 2019.
            /// </summary>

            [ColumnName(@"Prediction BoundingBox Height 2019")]
            public float Prediction_BoundingBox_Height_2019 { get; set; }
            /// <summary>
            /// Gets or sets the prediction confidence value for the year 2020.
            /// </summary>

            [ColumnName(@"Prediction Confidence 2020")]
            public float Prediction_Confidence_2020 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box X-coordinate for the year 2020.
            /// </summary>

            [ColumnName(@"Prediction BoundingBox X 2020")]
            public float Prediction_BoundingBox_X_2020 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box Y-coordinate for the year 2020.
            /// </summary>

            [ColumnName(@"Prediction BoundingBox Y 2020")]
            public float Prediction_BoundingBox_Y_2020 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box width for the year 2020.
            /// </summary>

            [ColumnName(@"Prediction BoundingBox Width 2020")]
            public float Prediction_BoundingBox_Width_2020 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box height for the year 2020.
            /// </summary>

            [ColumnName(@"Prediction BoundingBox Height 2020")]
            public float Prediction_BoundingBox_Height_2020 { get; set; }
            /// <summary>
            /// Gets or sets the prediction confidence value for the year 2021.
            /// </summary>

            [ColumnName(@"Prediction Confidence 2021")]
            public float Prediction_Confidence_2021 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box X-coordinate for the year 2021.
            /// </summary>

            [ColumnName(@"Prediction BoundingBox X 2021")]
            public float Prediction_BoundingBox_X_2021 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box Y-coordinate for the year 2021.
            /// </summary>

            [ColumnName(@"Prediction BoundingBox Y 2021")]
            public float Prediction_BoundingBox_Y_2021 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box width for the year 2021.
            /// </summary>

            [ColumnName(@"Prediction BoundingBox Width 2021")]
            public float Prediction_BoundingBox_Width_2021 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box height for the year 2021.
            /// </summary>

            [ColumnName(@"Prediction BoundingBox Height 2021")]
            public float Prediction_BoundingBox_Height_2021 { get; set; }
            /// <summary>
            /// Gets or sets the prediction confidence value for the year 2022.
            /// </summary>

            [ColumnName(@"Prediction Confidence 2022")]
            public float Prediction_Confidence_2022 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box X-coordinate for the year 2022.
            /// </summary>

            [ColumnName(@"Prediction BoundingBox X 2022")]
            public float Prediction_BoundingBox_X_2022 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box Y-coordinate for the year 2022.
            /// </summary>

            [ColumnName(@"Prediction BoundingBox Y 2022")]
            public float Prediction_BoundingBox_Y_2022 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box width for the year 2022.
            /// </summary>

            [ColumnName(@"Prediction BoundingBox Width 2022")]
            public float Prediction_BoundingBox_Width_2022 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box height for the year 2022.
            /// </summary>

            [ColumnName(@"Prediction BoundingBox Height 2022")]
            public float Prediction_BoundingBox_Height_2022 { get; set; }
            /// <summary>
            /// Gets or sets the prediction confidence value for the year 2023.
            /// </summary>

            [ColumnName(@"Prediction Confidence 2023")]
            public float Prediction_Confidence_2023 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box X-coordinate for the year 2023.
            /// </summary>

            [ColumnName(@"Prediction BoundingBox X 2023")]
            public float Prediction_BoundingBox_X_2023 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box Y-coordinate for the year 2023.
            /// </summary>

            [ColumnName(@"Prediction BoundingBox Y 2023")]
            public float Prediction_BoundingBox_Y_2023 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box width for the year 2023.
            /// </summary>

            [ColumnName(@"Prediction BoundingBox Width 2023")]
            public float Prediction_BoundingBox_Width_2023 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box height for the year 2023.
            /// </summary>

            [ColumnName(@"Prediction BoundingBox Height 2023")]
            public float Prediction_BoundingBox_Height_2023 { get; set; }
            /// <summary>
            /// Gets or sets the prediction confidence value for the year 2024.
            /// </summary>

            [ColumnName(@"Prediction Confidence 2024")]
            public float Prediction_Confidence_2024 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box X-coordinate for the year 2024.
            /// </summary>

            [ColumnName(@"Prediction BoundingBox X 2024")]
            public float Prediction_BoundingBox_X_2024 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box Y-coordinate for the year 2024.
            /// </summary>

            [ColumnName(@"Prediction BoundingBox Y 2024")]
            public float Prediction_BoundingBox_Y_2024 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box width for the year 2024.
            /// </summary>

            [ColumnName(@"Prediction BoundingBox Width 2024")]
            public float Prediction_BoundingBox_Width_2024 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box height for the year 2024.
            /// </summary>

            [ColumnName(@"Prediction BoundingBox Height 2024")]
            public float Prediction_BoundingBox_Height_2024 { get; set; }
            /// <summary>
            /// Gets or sets the prediction confidence value for the year 2025.
            /// </summary>

            [ColumnName(@"Prediction Confidence 2025")]
            public float Prediction_Confidence_2025 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box X-coordinate for the year 2025.
            /// </summary>

            [ColumnName(@"Prediction BoundingBox X 2025")]
            public float Prediction_BoundingBox_X_2025 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box Y-coordinate for the year 2025.
            /// </summary>

            [ColumnName(@"Prediction BoundingBox Y 2025")]
            public float Prediction_BoundingBox_Y_2025 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box width for the year 2025.
            /// </summary>

            [ColumnName(@"Prediction BoundingBox Width 2025")]
            public float Prediction_BoundingBox_Width_2025 { get; set; }
            /// <summary>
            /// Gets or sets the predicted bounding box height for the year 2025.
            /// </summary>

            [ColumnName(@"Prediction BoundingBox Height 2025")]
            public float Prediction_BoundingBox_Height_2025 { get; set; }
            /// <summary>
            /// Gets or sets the year the building was built.
            /// </summary>

            [ColumnName(@"Year Built")]
            public float Year_Built { get; set; }
            /// <summary>
            /// Gets or sets the features vector used by the model.
            /// </summary>

            [ColumnName(@"Features")]
            public float[] Features { get; set; } = [];
            /// <summary>
            /// Gets or sets the prediction score.
            /// </summary>

            [ColumnName(@"Score")]
            public float Score { get; set; }
        }

        #endregion model output class

        private static string MLNetModelPath
        {
            get
            {
                string fileName = "OrtoBuildingDetectionModel.mlnet";
                if (File.Exists(fileName))
                {
                    return Path.GetFullPath(fileName);
                }

                string pathBase = Path.Combine(AppContext.BaseDirectory, fileName);
                if (File.Exists(pathBase))
                {
                    return pathBase;
                }

                string? assemblyLocation = typeof(OrtoBuildingDetectionModel).Assembly.Location;
                if (!string.IsNullOrWhiteSpace(assemblyLocation))
                {
                    string pathAssembly = Path.Combine(Path.GetDirectoryName(assemblyLocation)!, fileName);
                    if (File.Exists(pathAssembly))
                    {
                        return pathAssembly;
                    }
                }

                string startDirectory = !string.IsNullOrWhiteSpace(assemblyLocation) ? Path.GetDirectoryName(assemblyLocation)! : AppContext.BaseDirectory;
                DirectoryInfo? directoryInfo = new(startDirectory);
                while (directoryInfo is not null && directoryInfo.Exists)
                {
                    string candidateRepo = Path.Combine(directoryInfo.FullName, "DiGi.GIS.ML", "DiGi.GIS.ML", fileName);
                    if (File.Exists(candidateRepo))
                    {
                        return candidateRepo;
                    }

                    string candidateDirect = Path.Combine(directoryInfo.FullName, fileName);
                    if (File.Exists(candidateDirect))
                    {
                        return candidateDirect;
                    }

                    string candidateBin = Path.Combine(directoryInfo.FullName, "bin", "Release", "net10.0", fileName);
                    if (File.Exists(candidateBin))
                    {
                        return candidateBin;
                    }

                    directoryInfo = directoryInfo.Parent;
                }

                return Path.GetFullPath(fileName);
            }
        }

        /// <summary>
        /// The prediction engine used to make single predictions on <see cref="ModelInput"/>.
        /// </summary>
        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new(CreatePredictEngine, true);

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            MLContext mlContext = new();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out DataViewSchema _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        private static readonly object predictLock = new();

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            lock (predictLock)
            {
                PredictionEngine<ModelInput, ModelOutput> predEngine = PredictEngine.Value;
                return predEngine.Predict(input);
            }
        }
    }
}
