// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace DiGi_GIS_ML
{
    public partial class OrtoBuildingDetectionModel
    {
        /// <summary>
        /// model input class for YearBuiltPrediction.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(1)]
            [ColumnName(@"Floor area")]
            public float Floor_area { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"Total area")]
            public float Total_area { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"Storeys")]
            public float Storeys { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"Azimuth")]
            public float Azimuth { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"Cardinal direction")]
            public string Cardinal_direction { get; set; } = string.Empty;

            [LoadColumn(6)]
            [ColumnName(@"Internal Point X")]
            public float Internal_Point_X { get; set; }

            [LoadColumn(7)]
            [ColumnName(@"Internal Point Y")]
            public float Internal_Point_Y { get; set; }

            [LoadColumn(8)]
            [ColumnName(@"BoundingBox X")]
            public float BoundingBox_X { get; set; }

            [LoadColumn(9)]
            [ColumnName(@"BoundingBox Y")]
            public float BoundingBox_Y { get; set; }

            [LoadColumn(10)]
            [ColumnName(@"BoundingBox width")]
            public float BoundingBox_width { get; set; }

            [LoadColumn(11)]
            [ColumnName(@"BoundingBox height")]
            public float BoundingBox_height { get; set; }

            [LoadColumn(12)]
            [ColumnName(@"Isoperimetric ratio")]
            public float Isoperimetric_ratio { get; set; }

            [LoadColumn(13)]
            [ColumnName(@"Rectangular thinnes ratio")]
            public float Rectangular_thinnes_ratio { get; set; }

            [LoadColumn(14)]
            [ColumnName(@"Square thinness ratio")]
            public float Square_thinness_ratio { get; set; }

            [LoadColumn(15)]
            [ColumnName(@"Thinness ratio")]
            public float Thinness_ratio { get; set; }

            [LoadColumn(16)]
            [ColumnName(@"Convex hull thinness ratio")]
            public float Convex_hull_thinness_ratio { get; set; }

            [LoadColumn(17)]
            [ColumnName(@"Calculated Building Shape")]
            public string Calculated_Building_Shape { get; set; } = string.Empty;

            [LoadColumn(18)]
            [ColumnName(@"Building general function")]
            public string Building_general_function { get; set; } = string.Empty;

            [LoadColumn(19)]
            [ColumnName(@"Building specific functions")]
            public string Building_specific_functions { get; set; } = string.Empty;

            [LoadColumn(20)]
            [ColumnName(@"Building Phase")]
            public string Building_Phase { get; set; } = string.Empty;

            [LoadColumn(21)]
            [ColumnName(@"Is residential")]
            public bool Is_residential { get; set; }

            [LoadColumn(22)]
            [ColumnName(@"Is occupied")]
            public bool Is_occupied { get; set; }

            [LoadColumn(23)]
            [ColumnName(@"Voivodeship name")]
            public string Voivodeship_name { get; set; } = string.Empty;

            [LoadColumn(24)]
            [ColumnName(@"County name")]
            public string County_name { get; set; } = string.Empty;

            [LoadColumn(25)]
            [ColumnName(@"County Id")]
            public float County_Id { get; set; }

            [LoadColumn(26)]
            [ColumnName(@"Municipality name")]
            public string Municipality_name { get; set; } = string.Empty;

            [LoadColumn(27)]
            [ColumnName(@"Subdivision name")]
            public string Subdivision_name { get; set; } = string.Empty;

            [LoadColumn(28)]
            [ColumnName(@"Subdivision Id")]
            public float Subdivision_Id { get; set; }

            [LoadColumn(29)]
            [ColumnName(@"Settlement type")]
            public string Settlement_type { get; set; } = string.Empty;

            [LoadColumn(30)]
            [ColumnName(@"Subdivision occupancy")]
            public float Subdivision_occupancy { get; set; }

            [LoadColumn(31)]
            [ColumnName(@"Calculated occupancy")]
            public float Calculated_occupancy { get; set; }

            [LoadColumn(32)]
            [ColumnName(@"Grid cell coverage [0,0]")]
            public float Grid_cell_coverage__0_0_ { get; set; }

            [LoadColumn(33)]
            [ColumnName(@"Grid cell coverage [0,1]")]
            public float Grid_cell_coverage__0_1_ { get; set; }

            [LoadColumn(34)]
            [ColumnName(@"Grid cell coverage [0,2]")]
            public float Grid_cell_coverage__0_2_ { get; set; }

            [LoadColumn(35)]
            [ColumnName(@"Grid cell coverage [0,3]")]
            public float Grid_cell_coverage__0_3_ { get; set; }

            [LoadColumn(36)]
            [ColumnName(@"Grid cell coverage [0,4]")]
            public float Grid_cell_coverage__0_4_ { get; set; }

            [LoadColumn(37)]
            [ColumnName(@"Grid cell coverage [1,0]")]
            public float Grid_cell_coverage__1_0_ { get; set; }

            [LoadColumn(38)]
            [ColumnName(@"Grid cell coverage [1,1]")]
            public float Grid_cell_coverage__1_1_ { get; set; }

            [LoadColumn(39)]
            [ColumnName(@"Grid cell coverage [1,2]")]
            public float Grid_cell_coverage__1_2_ { get; set; }

            [LoadColumn(40)]
            [ColumnName(@"Grid cell coverage [1,3]")]
            public float Grid_cell_coverage__1_3_ { get; set; }

            [LoadColumn(41)]
            [ColumnName(@"Grid cell coverage [1,4]")]
            public float Grid_cell_coverage__1_4_ { get; set; }

            [LoadColumn(42)]
            [ColumnName(@"Grid cell coverage [2,0]")]
            public float Grid_cell_coverage__2_0_ { get; set; }

            [LoadColumn(43)]
            [ColumnName(@"Grid cell coverage [2,1]")]
            public float Grid_cell_coverage__2_1_ { get; set; }

            [LoadColumn(44)]
            [ColumnName(@"Grid cell coverage [2,2]")]
            public float Grid_cell_coverage__2_2_ { get; set; }

            [LoadColumn(45)]
            [ColumnName(@"Grid cell coverage [2,3]")]
            public float Grid_cell_coverage__2_3_ { get; set; }

            [LoadColumn(46)]
            [ColumnName(@"Grid cell coverage [2,4]")]
            public float Grid_cell_coverage__2_4_ { get; set; }

            [LoadColumn(47)]
            [ColumnName(@"Grid cell coverage [3,0]")]
            public float Grid_cell_coverage__3_0_ { get; set; }

            [LoadColumn(48)]
            [ColumnName(@"Grid cell coverage [3,1]")]
            public float Grid_cell_coverage__3_1_ { get; set; }

            [LoadColumn(49)]
            [ColumnName(@"Grid cell coverage [3,2]")]
            public float Grid_cell_coverage__3_2_ { get; set; }

            [LoadColumn(50)]
            [ColumnName(@"Grid cell coverage [3,3]")]
            public float Grid_cell_coverage__3_3_ { get; set; }

            [LoadColumn(51)]
            [ColumnName(@"Grid cell coverage [3,4]")]
            public float Grid_cell_coverage__3_4_ { get; set; }

            [LoadColumn(52)]
            [ColumnName(@"Grid cell coverage [4,0]")]
            public float Grid_cell_coverage__4_0_ { get; set; }

            [LoadColumn(53)]
            [ColumnName(@"Grid cell coverage [4,1]")]
            public float Grid_cell_coverage__4_1_ { get; set; }

            [LoadColumn(54)]
            [ColumnName(@"Grid cell coverage [4,2]")]
            public float Grid_cell_coverage__4_2_ { get; set; }

            [LoadColumn(55)]
            [ColumnName(@"Grid cell coverage [4,3]")]
            public float Grid_cell_coverage__4_3_ { get; set; }

            [LoadColumn(56)]
            [ColumnName(@"Grid cell coverage [4,4]")]
            public float Grid_cell_coverage__4_4_ { get; set; }

            [LoadColumn(57)]
            [ColumnName(@"Prediction Confidence 2008")]
            public float Prediction_Confidence_2008 { get; set; }

            [LoadColumn(58)]
            [ColumnName(@"Prediction BoundingBox X 2008")]
            public float Prediction_BoundingBox_X_2008 { get; set; }

            [LoadColumn(59)]
            [ColumnName(@"Prediction BoundingBox Y 2008")]
            public float Prediction_BoundingBox_Y_2008 { get; set; }

            [LoadColumn(60)]
            [ColumnName(@"Prediction BoundingBox Width 2008")]
            public float Prediction_BoundingBox_Width_2008 { get; set; }

            [LoadColumn(61)]
            [ColumnName(@"Prediction BoundingBox Height 2008")]
            public float Prediction_BoundingBox_Height_2008 { get; set; }

            [LoadColumn(62)]
            [ColumnName(@"Prediction Confidence 2009")]
            public float Prediction_Confidence_2009 { get; set; }

            [LoadColumn(63)]
            [ColumnName(@"Prediction BoundingBox X 2009")]
            public float Prediction_BoundingBox_X_2009 { get; set; }

            [LoadColumn(64)]
            [ColumnName(@"Prediction BoundingBox Y 2009")]
            public float Prediction_BoundingBox_Y_2009 { get; set; }

            [LoadColumn(65)]
            [ColumnName(@"Prediction BoundingBox Width 2009")]
            public float Prediction_BoundingBox_Width_2009 { get; set; }

            [LoadColumn(66)]
            [ColumnName(@"Prediction BoundingBox Height 2009")]
            public float Prediction_BoundingBox_Height_2009 { get; set; }

            [LoadColumn(67)]
            [ColumnName(@"Prediction Confidence 2010")]
            public float Prediction_Confidence_2010 { get; set; }

            [LoadColumn(68)]
            [ColumnName(@"Prediction BoundingBox X 2010")]
            public float Prediction_BoundingBox_X_2010 { get; set; }

            [LoadColumn(69)]
            [ColumnName(@"Prediction BoundingBox Y 2010")]
            public float Prediction_BoundingBox_Y_2010 { get; set; }

            [LoadColumn(70)]
            [ColumnName(@"Prediction BoundingBox Width 2010")]
            public float Prediction_BoundingBox_Width_2010 { get; set; }

            [LoadColumn(71)]
            [ColumnName(@"Prediction BoundingBox Height 2010")]
            public float Prediction_BoundingBox_Height_2010 { get; set; }

            [LoadColumn(72)]
            [ColumnName(@"Prediction Confidence 2011")]
            public float Prediction_Confidence_2011 { get; set; }

            [LoadColumn(73)]
            [ColumnName(@"Prediction BoundingBox X 2011")]
            public float Prediction_BoundingBox_X_2011 { get; set; }

            [LoadColumn(74)]
            [ColumnName(@"Prediction BoundingBox Y 2011")]
            public float Prediction_BoundingBox_Y_2011 { get; set; }

            [LoadColumn(75)]
            [ColumnName(@"Prediction BoundingBox Width 2011")]
            public float Prediction_BoundingBox_Width_2011 { get; set; }

            [LoadColumn(76)]
            [ColumnName(@"Prediction BoundingBox Height 2011")]
            public float Prediction_BoundingBox_Height_2011 { get; set; }

            [LoadColumn(77)]
            [ColumnName(@"Prediction Confidence 2012")]
            public float Prediction_Confidence_2012 { get; set; }

            [LoadColumn(78)]
            [ColumnName(@"Prediction BoundingBox X 2012")]
            public float Prediction_BoundingBox_X_2012 { get; set; }

            [LoadColumn(79)]
            [ColumnName(@"Prediction BoundingBox Y 2012")]
            public float Prediction_BoundingBox_Y_2012 { get; set; }

            [LoadColumn(80)]
            [ColumnName(@"Prediction BoundingBox Width 2012")]
            public float Prediction_BoundingBox_Width_2012 { get; set; }

            [LoadColumn(81)]
            [ColumnName(@"Prediction BoundingBox Height 2012")]
            public float Prediction_BoundingBox_Height_2012 { get; set; }

            [LoadColumn(82)]
            [ColumnName(@"Prediction Confidence 2013")]
            public float Prediction_Confidence_2013 { get; set; }

            [LoadColumn(83)]
            [ColumnName(@"Prediction BoundingBox X 2013")]
            public float Prediction_BoundingBox_X_2013 { get; set; }

            [LoadColumn(84)]
            [ColumnName(@"Prediction BoundingBox Y 2013")]
            public float Prediction_BoundingBox_Y_2013 { get; set; }

            [LoadColumn(85)]
            [ColumnName(@"Prediction BoundingBox Width 2013")]
            public float Prediction_BoundingBox_Width_2013 { get; set; }

            [LoadColumn(86)]
            [ColumnName(@"Prediction BoundingBox Height 2013")]
            public float Prediction_BoundingBox_Height_2013 { get; set; }

            [LoadColumn(87)]
            [ColumnName(@"Prediction Confidence 2014")]
            public float Prediction_Confidence_2014 { get; set; }

            [LoadColumn(88)]
            [ColumnName(@"Prediction BoundingBox X 2014")]
            public float Prediction_BoundingBox_X_2014 { get; set; }

            [LoadColumn(89)]
            [ColumnName(@"Prediction BoundingBox Y 2014")]
            public float Prediction_BoundingBox_Y_2014 { get; set; }

            [LoadColumn(90)]
            [ColumnName(@"Prediction BoundingBox Width 2014")]
            public float Prediction_BoundingBox_Width_2014 { get; set; }

            [LoadColumn(91)]
            [ColumnName(@"Prediction BoundingBox Height 2014")]
            public float Prediction_BoundingBox_Height_2014 { get; set; }

            [LoadColumn(92)]
            [ColumnName(@"Prediction Confidence 2015")]
            public float Prediction_Confidence_2015 { get; set; }

            [LoadColumn(93)]
            [ColumnName(@"Prediction BoundingBox X 2015")]
            public float Prediction_BoundingBox_X_2015 { get; set; }

            [LoadColumn(94)]
            [ColumnName(@"Prediction BoundingBox Y 2015")]
            public float Prediction_BoundingBox_Y_2015 { get; set; }

            [LoadColumn(95)]
            [ColumnName(@"Prediction BoundingBox Width 2015")]
            public float Prediction_BoundingBox_Width_2015 { get; set; }

            [LoadColumn(96)]
            [ColumnName(@"Prediction BoundingBox Height 2015")]
            public float Prediction_BoundingBox_Height_2015 { get; set; }

            [LoadColumn(97)]
            [ColumnName(@"Prediction Confidence 2016")]
            public float Prediction_Confidence_2016 { get; set; }

            [LoadColumn(98)]
            [ColumnName(@"Prediction BoundingBox X 2016")]
            public float Prediction_BoundingBox_X_2016 { get; set; }

            [LoadColumn(99)]
            [ColumnName(@"Prediction BoundingBox Y 2016")]
            public float Prediction_BoundingBox_Y_2016 { get; set; }

            [LoadColumn(100)]
            [ColumnName(@"Prediction BoundingBox Width 2016")]
            public float Prediction_BoundingBox_Width_2016 { get; set; }

            [LoadColumn(101)]
            [ColumnName(@"Prediction BoundingBox Height 2016")]
            public float Prediction_BoundingBox_Height_2016 { get; set; }

            [LoadColumn(102)]
            [ColumnName(@"Prediction Confidence 2017")]
            public float Prediction_Confidence_2017 { get; set; }

            [LoadColumn(103)]
            [ColumnName(@"Prediction BoundingBox X 2017")]
            public float Prediction_BoundingBox_X_2017 { get; set; }

            [LoadColumn(104)]
            [ColumnName(@"Prediction BoundingBox Y 2017")]
            public float Prediction_BoundingBox_Y_2017 { get; set; }

            [LoadColumn(105)]
            [ColumnName(@"Prediction BoundingBox Width 2017")]
            public float Prediction_BoundingBox_Width_2017 { get; set; }

            [LoadColumn(106)]
            [ColumnName(@"Prediction BoundingBox Height 2017")]
            public float Prediction_BoundingBox_Height_2017 { get; set; }

            [LoadColumn(107)]
            [ColumnName(@"Prediction Confidence 2018")]
            public float Prediction_Confidence_2018 { get; set; }

            [LoadColumn(108)]
            [ColumnName(@"Prediction BoundingBox X 2018")]
            public float Prediction_BoundingBox_X_2018 { get; set; }

            [LoadColumn(109)]
            [ColumnName(@"Prediction BoundingBox Y 2018")]
            public float Prediction_BoundingBox_Y_2018 { get; set; }

            [LoadColumn(110)]
            [ColumnName(@"Prediction BoundingBox Width 2018")]
            public float Prediction_BoundingBox_Width_2018 { get; set; }

            [LoadColumn(111)]
            [ColumnName(@"Prediction BoundingBox Height 2018")]
            public float Prediction_BoundingBox_Height_2018 { get; set; }

            [LoadColumn(112)]
            [ColumnName(@"Prediction Confidence 2019")]
            public float Prediction_Confidence_2019 { get; set; }

            [LoadColumn(113)]
            [ColumnName(@"Prediction BoundingBox X 2019")]
            public float Prediction_BoundingBox_X_2019 { get; set; }

            [LoadColumn(114)]
            [ColumnName(@"Prediction BoundingBox Y 2019")]
            public float Prediction_BoundingBox_Y_2019 { get; set; }

            [LoadColumn(115)]
            [ColumnName(@"Prediction BoundingBox Width 2019")]
            public float Prediction_BoundingBox_Width_2019 { get; set; }

            [LoadColumn(116)]
            [ColumnName(@"Prediction BoundingBox Height 2019")]
            public float Prediction_BoundingBox_Height_2019 { get; set; }

            [LoadColumn(117)]
            [ColumnName(@"Prediction Confidence 2020")]
            public float Prediction_Confidence_2020 { get; set; }

            [LoadColumn(118)]
            [ColumnName(@"Prediction BoundingBox X 2020")]
            public float Prediction_BoundingBox_X_2020 { get; set; }

            [LoadColumn(119)]
            [ColumnName(@"Prediction BoundingBox Y 2020")]
            public float Prediction_BoundingBox_Y_2020 { get; set; }

            [LoadColumn(120)]
            [ColumnName(@"Prediction BoundingBox Width 2020")]
            public float Prediction_BoundingBox_Width_2020 { get; set; }

            [LoadColumn(121)]
            [ColumnName(@"Prediction BoundingBox Height 2020")]
            public float Prediction_BoundingBox_Height_2020 { get; set; }

            [LoadColumn(122)]
            [ColumnName(@"Prediction Confidence 2021")]
            public float Prediction_Confidence_2021 { get; set; }

            [LoadColumn(123)]
            [ColumnName(@"Prediction BoundingBox X 2021")]
            public float Prediction_BoundingBox_X_2021 { get; set; }

            [LoadColumn(124)]
            [ColumnName(@"Prediction BoundingBox Y 2021")]
            public float Prediction_BoundingBox_Y_2021 { get; set; }

            [LoadColumn(125)]
            [ColumnName(@"Prediction BoundingBox Width 2021")]
            public float Prediction_BoundingBox_Width_2021 { get; set; }

            [LoadColumn(126)]
            [ColumnName(@"Prediction BoundingBox Height 2021")]
            public float Prediction_BoundingBox_Height_2021 { get; set; }

            [LoadColumn(127)]
            [ColumnName(@"Prediction Confidence 2022")]
            public float Prediction_Confidence_2022 { get; set; }

            [LoadColumn(128)]
            [ColumnName(@"Prediction BoundingBox X 2022")]
            public float Prediction_BoundingBox_X_2022 { get; set; }

            [LoadColumn(129)]
            [ColumnName(@"Prediction BoundingBox Y 2022")]
            public float Prediction_BoundingBox_Y_2022 { get; set; }

            [LoadColumn(130)]
            [ColumnName(@"Prediction BoundingBox Width 2022")]
            public float Prediction_BoundingBox_Width_2022 { get; set; }

            [LoadColumn(131)]
            [ColumnName(@"Prediction BoundingBox Height 2022")]
            public float Prediction_BoundingBox_Height_2022 { get; set; }

            [LoadColumn(132)]
            [ColumnName(@"Prediction Confidence 2023")]
            public float Prediction_Confidence_2023 { get; set; }

            [LoadColumn(133)]
            [ColumnName(@"Prediction BoundingBox X 2023")]
            public float Prediction_BoundingBox_X_2023 { get; set; }

            [LoadColumn(134)]
            [ColumnName(@"Prediction BoundingBox Y 2023")]
            public float Prediction_BoundingBox_Y_2023 { get; set; }

            [LoadColumn(135)]
            [ColumnName(@"Prediction BoundingBox Width 2023")]
            public float Prediction_BoundingBox_Width_2023 { get; set; }

            [LoadColumn(136)]
            [ColumnName(@"Prediction BoundingBox Height 2023")]
            public float Prediction_BoundingBox_Height_2023 { get; set; }

            [LoadColumn(137)]
            [ColumnName(@"Prediction Confidence 2024")]
            public float Prediction_Confidence_2024 { get; set; }

            [LoadColumn(138)]
            [ColumnName(@"Prediction BoundingBox X 2024")]
            public float Prediction_BoundingBox_X_2024 { get; set; }

            [LoadColumn(139)]
            [ColumnName(@"Prediction BoundingBox Y 2024")]
            public float Prediction_BoundingBox_Y_2024 { get; set; }

            [LoadColumn(140)]
            [ColumnName(@"Prediction BoundingBox Width 2024")]
            public float Prediction_BoundingBox_Width_2024 { get; set; }

            [LoadColumn(141)]
            [ColumnName(@"Prediction BoundingBox Height 2024")]
            public float Prediction_BoundingBox_Height_2024 { get; set; }

            [LoadColumn(142)]
            [ColumnName(@"Prediction Confidence 2025")]
            public float Prediction_Confidence_2025 { get; set; }

            [LoadColumn(143)]
            [ColumnName(@"Prediction BoundingBox X 2025")]
            public float Prediction_BoundingBox_X_2025 { get; set; }

            [LoadColumn(144)]
            [ColumnName(@"Prediction BoundingBox Y 2025")]
            public float Prediction_BoundingBox_Y_2025 { get; set; }

            [LoadColumn(145)]
            [ColumnName(@"Prediction BoundingBox Width 2025")]
            public float Prediction_BoundingBox_Width_2025 { get; set; }

            [LoadColumn(146)]
            [ColumnName(@"Prediction BoundingBox Height 2025")]
            public float Prediction_BoundingBox_Height_2025 { get; set; }

            [LoadColumn(147)]
            [ColumnName(@"Municipality population 2008")]
            public float Municipality_population_2008 { get; set; }

            [LoadColumn(148)]
            [ColumnName(@"Municipality population 2009")]
            public float Municipality_population_2009 { get; set; }

            [LoadColumn(149)]
            [ColumnName(@"Municipality population 2010")]
            public float Municipality_population_2010 { get; set; }

            [LoadColumn(150)]
            [ColumnName(@"Municipality population 2011")]
            public float Municipality_population_2011 { get; set; }

            [LoadColumn(151)]
            [ColumnName(@"Municipality population 2012")]
            public float Municipality_population_2012 { get; set; }

            [LoadColumn(152)]
            [ColumnName(@"Municipality population 2013")]
            public float Municipality_population_2013 { get; set; }

            [LoadColumn(153)]
            [ColumnName(@"Municipality population 2014")]
            public float Municipality_population_2014 { get; set; }

            [LoadColumn(154)]
            [ColumnName(@"Municipality population 2015")]
            public float Municipality_population_2015 { get; set; }

            [LoadColumn(155)]
            [ColumnName(@"Municipality population 2016")]
            public float Municipality_population_2016 { get; set; }

            [LoadColumn(156)]
            [ColumnName(@"Municipality population 2017")]
            public float Municipality_population_2017 { get; set; }

            [LoadColumn(157)]
            [ColumnName(@"Municipality population 2018")]
            public float Municipality_population_2018 { get; set; }

            [LoadColumn(158)]
            [ColumnName(@"Municipality population 2019")]
            public float Municipality_population_2019 { get; set; }

            [LoadColumn(159)]
            [ColumnName(@"Municipality population 2020")]
            public float Municipality_population_2020 { get; set; }

            [LoadColumn(160)]
            [ColumnName(@"Municipality population 2021")]
            public float Municipality_population_2021 { get; set; }

            [LoadColumn(161)]
            [ColumnName(@"Municipality population 2022")]
            public float Municipality_population_2022 { get; set; }

            [LoadColumn(162)]
            [ColumnName(@"Municipality population 2023")]
            public float Municipality_population_2023 { get; set; }

            [LoadColumn(163)]
            [ColumnName(@"Municipality population 2024")]
            public float Municipality_population_2024 { get; set; }

            [LoadColumn(164)]
            [ColumnName(@"Municipality population 2025")]
            public float Municipality_population_2025 { get; set; }

            [LoadColumn(165)]
            [ColumnName(@"Radial Building Coverage Ratio 200m")]
            public float Radial_Building_Coverage_Ratio_200m { get; set; }

            [LoadColumn(166)]
            [ColumnName(@"Radial Floor Area Ratio 200m")]
            public float Radial_Floor_Area_Ratio_200m { get; set; }

            [LoadColumn(167)]
            [ColumnName(@"Radial Building Coverage Ratio 400m")]
            public float Radial_Building_Coverage_Ratio_400m { get; set; }

            [LoadColumn(168)]
            [ColumnName(@"Radial Floor Area Ratio 400m")]
            public float Radial_Floor_Area_Ratio_400m { get; set; }

            [LoadColumn(169)]
            [ColumnName(@"Radial Building Coverage Ratio 600m")]
            public float Radial_Building_Coverage_Ratio_600m { get; set; }

            [LoadColumn(170)]
            [ColumnName(@"Radial Floor Area Ratio 600m")]
            public float Radial_Floor_Area_Ratio_600m { get; set; }

            [LoadColumn(171)]
            [ColumnName(@"Radial Building Coverage Ratio 1000m")]
            public float Radial_Building_Coverage_Ratio_1000m { get; set; }

            [LoadColumn(172)]
            [ColumnName(@"Radial Floor Area Ratio 1000m")]
            public float Radial_Floor_Area_Ratio_1000m { get; set; }

            [LoadColumn(173)]
            [ColumnName(@"Year built")]
            public float Year_built { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for YearBuiltPrediction.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"Floor area")]
            public float Floor_area { get; set; }

            [ColumnName(@"Total area")]
            public float Total_area { get; set; }

            [ColumnName(@"Storeys")]
            public float Storeys { get; set; }

            [ColumnName(@"Azimuth")]
            public float Azimuth { get; set; }

            [ColumnName(@"Cardinal direction")]
            public float[] Cardinal_direction { get; set; } = [];

            [ColumnName(@"Internal Point X")]
            public float Internal_Point_X { get; set; }

            [ColumnName(@"Internal Point Y")]
            public float Internal_Point_Y { get; set; }

            [ColumnName(@"BoundingBox X")]
            public float BoundingBox_X { get; set; }

            [ColumnName(@"BoundingBox Y")]
            public float BoundingBox_Y { get; set; }

            [ColumnName(@"BoundingBox width")]
            public float BoundingBox_width { get; set; }

            [ColumnName(@"BoundingBox height")]
            public float BoundingBox_height { get; set; }

            [ColumnName(@"Isoperimetric ratio")]
            public float Isoperimetric_ratio { get; set; }

            [ColumnName(@"Rectangular thinnes ratio")]
            public float Rectangular_thinnes_ratio { get; set; }

            [ColumnName(@"Square thinness ratio")]
            public float Square_thinness_ratio { get; set; }

            [ColumnName(@"Thinness ratio")]
            public float Thinness_ratio { get; set; }

            [ColumnName(@"Convex hull thinness ratio")]
            public float Convex_hull_thinness_ratio { get; set; }

            [ColumnName(@"Calculated Building Shape")]
            public float[] Calculated_Building_Shape { get; set; } = [];

            [ColumnName(@"Building general function")]
            public float[] Building_general_function { get; set; } = [];

            [ColumnName(@"Building specific functions")]
            public float[] Building_specific_functions { get; set; } = [];

            [ColumnName(@"Building Phase")]
            public float[] Building_Phase { get; set; } = [];

            [ColumnName(@"Is residential")]
            public float[] Is_residential { get; set; } = [];

            [ColumnName(@"Is occupied")]
            public float[] Is_occupied { get; set; } = [];

            [ColumnName(@"Voivodeship name")]
            public float[] Voivodeship_name { get; set; } = [];

            [ColumnName(@"County name")]
            public float[] County_name { get; set; } = [];

            [ColumnName(@"County Id")]
            public float County_Id { get; set; }

            [ColumnName(@"Municipality name")]
            public float[] Municipality_name { get; set; } = [];

            [ColumnName(@"Subdivision name")]
            public float[] Subdivision_name { get; set; } = [];

            [ColumnName(@"Subdivision Id")]
            public float Subdivision_Id { get; set; }

            [ColumnName(@"Settlement type")]
            public float[] Settlement_type { get; set; } = [];

            [ColumnName(@"Subdivision occupancy")]
            public float Subdivision_occupancy { get; set; }

            [ColumnName(@"Calculated occupancy")]
            public float Calculated_occupancy { get; set; }

            [ColumnName(@"Grid cell coverage [0,0]")]
            public float Grid_cell_coverage__0_0_ { get; set; }

            [ColumnName(@"Grid cell coverage [0,1]")]
            public float Grid_cell_coverage__0_1_ { get; set; }

            [ColumnName(@"Grid cell coverage [0,2]")]
            public float Grid_cell_coverage__0_2_ { get; set; }

            [ColumnName(@"Grid cell coverage [0,3]")]
            public float Grid_cell_coverage__0_3_ { get; set; }

            [ColumnName(@"Grid cell coverage [0,4]")]
            public float Grid_cell_coverage__0_4_ { get; set; }

            [ColumnName(@"Grid cell coverage [1,0]")]
            public float Grid_cell_coverage__1_0_ { get; set; }

            [ColumnName(@"Grid cell coverage [1,1]")]
            public float Grid_cell_coverage__1_1_ { get; set; }

            [ColumnName(@"Grid cell coverage [1,2]")]
            public float Grid_cell_coverage__1_2_ { get; set; }

            [ColumnName(@"Grid cell coverage [1,3]")]
            public float Grid_cell_coverage__1_3_ { get; set; }

            [ColumnName(@"Grid cell coverage [1,4]")]
            public float Grid_cell_coverage__1_4_ { get; set; }

            [ColumnName(@"Grid cell coverage [2,0]")]
            public float Grid_cell_coverage__2_0_ { get; set; }

            [ColumnName(@"Grid cell coverage [2,1]")]
            public float Grid_cell_coverage__2_1_ { get; set; }

            [ColumnName(@"Grid cell coverage [2,2]")]
            public float Grid_cell_coverage__2_2_ { get; set; }

            [ColumnName(@"Grid cell coverage [2,3]")]
            public float Grid_cell_coverage__2_3_ { get; set; }

            [ColumnName(@"Grid cell coverage [2,4]")]
            public float Grid_cell_coverage__2_4_ { get; set; }

            [ColumnName(@"Grid cell coverage [3,0]")]
            public float Grid_cell_coverage__3_0_ { get; set; }

            [ColumnName(@"Grid cell coverage [3,1]")]
            public float Grid_cell_coverage__3_1_ { get; set; }

            [ColumnName(@"Grid cell coverage [3,2]")]
            public float Grid_cell_coverage__3_2_ { get; set; }

            [ColumnName(@"Grid cell coverage [3,3]")]
            public float Grid_cell_coverage__3_3_ { get; set; }

            [ColumnName(@"Grid cell coverage [3,4]")]
            public float Grid_cell_coverage__3_4_ { get; set; }

            [ColumnName(@"Grid cell coverage [4,0]")]
            public float Grid_cell_coverage__4_0_ { get; set; }

            [ColumnName(@"Grid cell coverage [4,1]")]
            public float Grid_cell_coverage__4_1_ { get; set; }

            [ColumnName(@"Grid cell coverage [4,2]")]
            public float Grid_cell_coverage__4_2_ { get; set; }

            [ColumnName(@"Grid cell coverage [4,3]")]
            public float Grid_cell_coverage__4_3_ { get; set; }

            [ColumnName(@"Grid cell coverage [4,4]")]
            public float Grid_cell_coverage__4_4_ { get; set; }

            [ColumnName(@"Prediction Confidence 2008")]
            public float Prediction_Confidence_2008 { get; set; }

            [ColumnName(@"Prediction BoundingBox X 2008")]
            public float Prediction_BoundingBox_X_2008 { get; set; }

            [ColumnName(@"Prediction BoundingBox Y 2008")]
            public float Prediction_BoundingBox_Y_2008 { get; set; }

            [ColumnName(@"Prediction BoundingBox Width 2008")]
            public float Prediction_BoundingBox_Width_2008 { get; set; }

            [ColumnName(@"Prediction BoundingBox Height 2008")]
            public float Prediction_BoundingBox_Height_2008 { get; set; }

            [ColumnName(@"Prediction Confidence 2009")]
            public float Prediction_Confidence_2009 { get; set; }

            [ColumnName(@"Prediction BoundingBox X 2009")]
            public float Prediction_BoundingBox_X_2009 { get; set; }

            [ColumnName(@"Prediction BoundingBox Y 2009")]
            public float Prediction_BoundingBox_Y_2009 { get; set; }

            [ColumnName(@"Prediction BoundingBox Width 2009")]
            public float Prediction_BoundingBox_Width_2009 { get; set; }

            [ColumnName(@"Prediction BoundingBox Height 2009")]
            public float Prediction_BoundingBox_Height_2009 { get; set; }

            [ColumnName(@"Prediction Confidence 2010")]
            public float Prediction_Confidence_2010 { get; set; }

            [ColumnName(@"Prediction BoundingBox X 2010")]
            public float Prediction_BoundingBox_X_2010 { get; set; }

            [ColumnName(@"Prediction BoundingBox Y 2010")]
            public float Prediction_BoundingBox_Y_2010 { get; set; }

            [ColumnName(@"Prediction BoundingBox Width 2010")]
            public float Prediction_BoundingBox_Width_2010 { get; set; }

            [ColumnName(@"Prediction BoundingBox Height 2010")]
            public float Prediction_BoundingBox_Height_2010 { get; set; }

            [ColumnName(@"Prediction Confidence 2011")]
            public float Prediction_Confidence_2011 { get; set; }

            [ColumnName(@"Prediction BoundingBox X 2011")]
            public float Prediction_BoundingBox_X_2011 { get; set; }

            [ColumnName(@"Prediction BoundingBox Y 2011")]
            public float Prediction_BoundingBox_Y_2011 { get; set; }

            [ColumnName(@"Prediction BoundingBox Width 2011")]
            public float Prediction_BoundingBox_Width_2011 { get; set; }

            [ColumnName(@"Prediction BoundingBox Height 2011")]
            public float Prediction_BoundingBox_Height_2011 { get; set; }

            [ColumnName(@"Prediction Confidence 2012")]
            public float Prediction_Confidence_2012 { get; set; }

            [ColumnName(@"Prediction BoundingBox X 2012")]
            public float Prediction_BoundingBox_X_2012 { get; set; }

            [ColumnName(@"Prediction BoundingBox Y 2012")]
            public float Prediction_BoundingBox_Y_2012 { get; set; }

            [ColumnName(@"Prediction BoundingBox Width 2012")]
            public float Prediction_BoundingBox_Width_2012 { get; set; }

            [ColumnName(@"Prediction BoundingBox Height 2012")]
            public float Prediction_BoundingBox_Height_2012 { get; set; }

            [ColumnName(@"Prediction Confidence 2013")]
            public float Prediction_Confidence_2013 { get; set; }

            [ColumnName(@"Prediction BoundingBox X 2013")]
            public float Prediction_BoundingBox_X_2013 { get; set; }

            [ColumnName(@"Prediction BoundingBox Y 2013")]
            public float Prediction_BoundingBox_Y_2013 { get; set; }

            [ColumnName(@"Prediction BoundingBox Width 2013")]
            public float Prediction_BoundingBox_Width_2013 { get; set; }

            [ColumnName(@"Prediction BoundingBox Height 2013")]
            public float Prediction_BoundingBox_Height_2013 { get; set; }

            [ColumnName(@"Prediction Confidence 2014")]
            public float Prediction_Confidence_2014 { get; set; }

            [ColumnName(@"Prediction BoundingBox X 2014")]
            public float Prediction_BoundingBox_X_2014 { get; set; }

            [ColumnName(@"Prediction BoundingBox Y 2014")]
            public float Prediction_BoundingBox_Y_2014 { get; set; }

            [ColumnName(@"Prediction BoundingBox Width 2014")]
            public float Prediction_BoundingBox_Width_2014 { get; set; }

            [ColumnName(@"Prediction BoundingBox Height 2014")]
            public float Prediction_BoundingBox_Height_2014 { get; set; }

            [ColumnName(@"Prediction Confidence 2015")]
            public float Prediction_Confidence_2015 { get; set; }

            [ColumnName(@"Prediction BoundingBox X 2015")]
            public float Prediction_BoundingBox_X_2015 { get; set; }

            [ColumnName(@"Prediction BoundingBox Y 2015")]
            public float Prediction_BoundingBox_Y_2015 { get; set; }

            [ColumnName(@"Prediction BoundingBox Width 2015")]
            public float Prediction_BoundingBox_Width_2015 { get; set; }

            [ColumnName(@"Prediction BoundingBox Height 2015")]
            public float Prediction_BoundingBox_Height_2015 { get; set; }

            [ColumnName(@"Prediction Confidence 2016")]
            public float Prediction_Confidence_2016 { get; set; }

            [ColumnName(@"Prediction BoundingBox X 2016")]
            public float Prediction_BoundingBox_X_2016 { get; set; }

            [ColumnName(@"Prediction BoundingBox Y 2016")]
            public float Prediction_BoundingBox_Y_2016 { get; set; }

            [ColumnName(@"Prediction BoundingBox Width 2016")]
            public float Prediction_BoundingBox_Width_2016 { get; set; }

            [ColumnName(@"Prediction BoundingBox Height 2016")]
            public float Prediction_BoundingBox_Height_2016 { get; set; }

            [ColumnName(@"Prediction Confidence 2017")]
            public float Prediction_Confidence_2017 { get; set; }

            [ColumnName(@"Prediction BoundingBox X 2017")]
            public float Prediction_BoundingBox_X_2017 { get; set; }

            [ColumnName(@"Prediction BoundingBox Y 2017")]
            public float Prediction_BoundingBox_Y_2017 { get; set; }

            [ColumnName(@"Prediction BoundingBox Width 2017")]
            public float Prediction_BoundingBox_Width_2017 { get; set; }

            [ColumnName(@"Prediction BoundingBox Height 2017")]
            public float Prediction_BoundingBox_Height_2017 { get; set; }

            [ColumnName(@"Prediction Confidence 2018")]
            public float Prediction_Confidence_2018 { get; set; }

            [ColumnName(@"Prediction BoundingBox X 2018")]
            public float Prediction_BoundingBox_X_2018 { get; set; }

            [ColumnName(@"Prediction BoundingBox Y 2018")]
            public float Prediction_BoundingBox_Y_2018 { get; set; }

            [ColumnName(@"Prediction BoundingBox Width 2018")]
            public float Prediction_BoundingBox_Width_2018 { get; set; }

            [ColumnName(@"Prediction BoundingBox Height 2018")]
            public float Prediction_BoundingBox_Height_2018 { get; set; }

            [ColumnName(@"Prediction Confidence 2019")]
            public float Prediction_Confidence_2019 { get; set; }

            [ColumnName(@"Prediction BoundingBox X 2019")]
            public float Prediction_BoundingBox_X_2019 { get; set; }

            [ColumnName(@"Prediction BoundingBox Y 2019")]
            public float Prediction_BoundingBox_Y_2019 { get; set; }

            [ColumnName(@"Prediction BoundingBox Width 2019")]
            public float Prediction_BoundingBox_Width_2019 { get; set; }

            [ColumnName(@"Prediction BoundingBox Height 2019")]
            public float Prediction_BoundingBox_Height_2019 { get; set; }

            [ColumnName(@"Prediction Confidence 2020")]
            public float Prediction_Confidence_2020 { get; set; }

            [ColumnName(@"Prediction BoundingBox X 2020")]
            public float Prediction_BoundingBox_X_2020 { get; set; }

            [ColumnName(@"Prediction BoundingBox Y 2020")]
            public float Prediction_BoundingBox_Y_2020 { get; set; }

            [ColumnName(@"Prediction BoundingBox Width 2020")]
            public float Prediction_BoundingBox_Width_2020 { get; set; }

            [ColumnName(@"Prediction BoundingBox Height 2020")]
            public float Prediction_BoundingBox_Height_2020 { get; set; }

            [ColumnName(@"Prediction Confidence 2021")]
            public float Prediction_Confidence_2021 { get; set; }

            [ColumnName(@"Prediction BoundingBox X 2021")]
            public float Prediction_BoundingBox_X_2021 { get; set; }

            [ColumnName(@"Prediction BoundingBox Y 2021")]
            public float Prediction_BoundingBox_Y_2021 { get; set; }

            [ColumnName(@"Prediction BoundingBox Width 2021")]
            public float Prediction_BoundingBox_Width_2021 { get; set; }

            [ColumnName(@"Prediction BoundingBox Height 2021")]
            public float Prediction_BoundingBox_Height_2021 { get; set; }

            [ColumnName(@"Prediction Confidence 2022")]
            public float Prediction_Confidence_2022 { get; set; }

            [ColumnName(@"Prediction BoundingBox X 2022")]
            public float Prediction_BoundingBox_X_2022 { get; set; }

            [ColumnName(@"Prediction BoundingBox Y 2022")]
            public float Prediction_BoundingBox_Y_2022 { get; set; }

            [ColumnName(@"Prediction BoundingBox Width 2022")]
            public float Prediction_BoundingBox_Width_2022 { get; set; }

            [ColumnName(@"Prediction BoundingBox Height 2022")]
            public float Prediction_BoundingBox_Height_2022 { get; set; }

            [ColumnName(@"Prediction Confidence 2023")]
            public float Prediction_Confidence_2023 { get; set; }

            [ColumnName(@"Prediction BoundingBox X 2023")]
            public float Prediction_BoundingBox_X_2023 { get; set; }

            [ColumnName(@"Prediction BoundingBox Y 2023")]
            public float Prediction_BoundingBox_Y_2023 { get; set; }

            [ColumnName(@"Prediction BoundingBox Width 2023")]
            public float Prediction_BoundingBox_Width_2023 { get; set; }

            [ColumnName(@"Prediction BoundingBox Height 2023")]
            public float Prediction_BoundingBox_Height_2023 { get; set; }

            [ColumnName(@"Prediction Confidence 2024")]
            public float Prediction_Confidence_2024 { get; set; }

            [ColumnName(@"Prediction BoundingBox X 2024")]
            public float Prediction_BoundingBox_X_2024 { get; set; }

            [ColumnName(@"Prediction BoundingBox Y 2024")]
            public float Prediction_BoundingBox_Y_2024 { get; set; }

            [ColumnName(@"Prediction BoundingBox Width 2024")]
            public float Prediction_BoundingBox_Width_2024 { get; set; }

            [ColumnName(@"Prediction BoundingBox Height 2024")]
            public float Prediction_BoundingBox_Height_2024 { get; set; }

            [ColumnName(@"Prediction Confidence 2025")]
            public float Prediction_Confidence_2025 { get; set; }

            [ColumnName(@"Prediction BoundingBox X 2025")]
            public float Prediction_BoundingBox_X_2025 { get; set; }

            [ColumnName(@"Prediction BoundingBox Y 2025")]
            public float Prediction_BoundingBox_Y_2025 { get; set; }

            [ColumnName(@"Prediction BoundingBox Width 2025")]
            public float Prediction_BoundingBox_Width_2025 { get; set; }

            [ColumnName(@"Prediction BoundingBox Height 2025")]
            public float Prediction_BoundingBox_Height_2025 { get; set; }

            [ColumnName(@"Municipality population 2008")]
            public float Municipality_population_2008 { get; set; }

            [ColumnName(@"Municipality population 2009")]
            public float Municipality_population_2009 { get; set; }

            [ColumnName(@"Municipality population 2010")]
            public float Municipality_population_2010 { get; set; }

            [ColumnName(@"Municipality population 2011")]
            public float Municipality_population_2011 { get; set; }

            [ColumnName(@"Municipality population 2012")]
            public float Municipality_population_2012 { get; set; }

            [ColumnName(@"Municipality population 2013")]
            public float Municipality_population_2013 { get; set; }

            [ColumnName(@"Municipality population 2014")]
            public float Municipality_population_2014 { get; set; }

            [ColumnName(@"Municipality population 2015")]
            public float Municipality_population_2015 { get; set; }

            [ColumnName(@"Municipality population 2016")]
            public float Municipality_population_2016 { get; set; }

            [ColumnName(@"Municipality population 2017")]
            public float Municipality_population_2017 { get; set; }

            [ColumnName(@"Municipality population 2018")]
            public float Municipality_population_2018 { get; set; }

            [ColumnName(@"Municipality population 2019")]
            public float Municipality_population_2019 { get; set; }

            [ColumnName(@"Municipality population 2020")]
            public float Municipality_population_2020 { get; set; }

            [ColumnName(@"Municipality population 2021")]
            public float Municipality_population_2021 { get; set; }

            [ColumnName(@"Municipality population 2022")]
            public float Municipality_population_2022 { get; set; }

            [ColumnName(@"Municipality population 2023")]
            public float Municipality_population_2023 { get; set; }

            [ColumnName(@"Municipality population 2024")]
            public float Municipality_population_2024 { get; set; }

            [ColumnName(@"Municipality population 2025")]
            public float Municipality_population_2025 { get; set; }

            [ColumnName(@"Radial Building Coverage Ratio 200m")]
            public float Radial_Building_Coverage_Ratio_200m { get; set; }

            [ColumnName(@"Radial Floor Area Ratio 200m")]
            public float Radial_Floor_Area_Ratio_200m { get; set; }

            [ColumnName(@"Radial Building Coverage Ratio 400m")]
            public float Radial_Building_Coverage_Ratio_400m { get; set; }

            [ColumnName(@"Radial Floor Area Ratio 400m")]
            public float Radial_Floor_Area_Ratio_400m { get; set; }

            [ColumnName(@"Radial Building Coverage Ratio 600m")]
            public float Radial_Building_Coverage_Ratio_600m { get; set; }

            [ColumnName(@"Radial Floor Area Ratio 600m")]
            public float Radial_Floor_Area_Ratio_600m { get; set; }

            [ColumnName(@"Radial Building Coverage Ratio 1000m")]
            public float Radial_Building_Coverage_Ratio_1000m { get; set; }

            [ColumnName(@"Radial Floor Area Ratio 1000m")]
            public float Radial_Floor_Area_Ratio_1000m { get; set; }

            [ColumnName(@"Year built")]
            public float Year_built { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; } = [];

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath
        {
            get
            {
                string fileName = "OrtoBuildingDetectionModel.mlnet";
                if (File.Exists(fileName))
                {
                    return Path.GetFullPath(fileName);
                }

                string pathBase = Path.Combine(AppContext.BaseDirectory, fileName);
                if (File.Exists(pathBase))
                {
                    return pathBase;
                }

                string? assemblyLocation = typeof(OrtoBuildingDetectionModel).Assembly.Location;
                if (!string.IsNullOrWhiteSpace(assemblyLocation))
                {
                    string pathAssembly = Path.Combine(Path.GetDirectoryName(assemblyLocation)!, fileName);
                    if (File.Exists(pathAssembly))
                    {
                        return pathAssembly;
                    }
                }

                string startDirectory = !string.IsNullOrWhiteSpace(assemblyLocation) ? Path.GetDirectoryName(assemblyLocation)! : AppContext.BaseDirectory;
                DirectoryInfo? directoryInfo = new(startDirectory);
                while (directoryInfo is not null && directoryInfo.Exists)
                {
                    string candidateRepo = Path.Combine(directoryInfo.FullName, "DiGi.GIS.ML", "DiGi.GIS.ML", fileName);
                    if (File.Exists(candidateRepo))
                    {
                        return candidateRepo;
                    }

                    string candidateDirect = Path.Combine(directoryInfo.FullName, fileName);
                    if (File.Exists(candidateDirect))
                    {
                        return candidateDirect;
                    }

                    string candidateBin = Path.Combine(directoryInfo.FullName, "bin", "Release", "net10.0", fileName);
                    if (File.Exists(candidateBin))
                    {
                        return candidateBin;
                    }

                    directoryInfo = directoryInfo.Parent;
                }

                return Path.GetFullPath(fileName);
            }
        }

        /// <summary>
        /// The prediction engine used to make single predictions on <see cref="ModelInput"/>.
        /// </summary>
        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new(CreatePredictEngine, true);

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            MLContext mlContext = new();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out DataViewSchema _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        private static readonly object predictLock = new();

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            lock (predictLock)
            {
                PredictionEngine<ModelInput, ModelOutput> predEngine = PredictEngine.Value;
                return predEngine.Predict(input);
            }
        }
    }
}
