// This file was auto-generated by ML.NET Model Builder.

using OrtoBuildingDetectionModelConsoleApp;
using DiGi.Core.IO.Table.Classes;

string path_Input = @"C:\Users\jakub\Downloads\GIS\ML_Input.tsv";
string path_Output = @"C:\Users\jakub\Downloads\GIS\ML_Output.tsv";

Table? table = DiGi.Core.IO.DelimitedData.Create.Table(path_Input, DiGi.Core.IO.DelimitedData.Enums.DelimitedDataSeparator.Tab);
if (table != null)
{
    List<Column>? columns = table.Columns?.ToList();
    if (columns != null && columns.Count != 0)
    {
        int index_Reference = columns.FindIndex(x => x.Name == "Reference");
        int index_BuildingGeneralFunction = columns.FindIndex(x => x.Name == "Building General Function");
        int index_BuildingPhase = columns.FindIndex(x => x.Name == "Building Phase");
        int index_Storeys = columns.FindIndex(x => x.Name == "Storeys");
        int index_Area = columns.FindIndex(x => x.Name == "Area");
        int index_Location_X = columns.FindIndex(x => x.Name == "Location X");
        int index_Location_Y = columns.FindIndex(x => x.Name == "Location Y");
        int index_Voivodeship = columns.FindIndex(x => x.Name == "Voivodeship");
        int index_County = columns.FindIndex(x => x.Name == "County");
        int index_Municipality = columns.FindIndex(x => x.Name == "Municipality");
        int index_Subdivision = columns.FindIndex(x => x.Name == "Subdivision");
        int index_SubdivisionCalculatedOccupancy = columns.FindIndex(x => x.Name == "Subdivision Calculated Occupancy");
        int index_SubdivisionCalculatedOccupancyArea = columns.FindIndex(x => x.Name == "Subdivision Calculated Occupancy Area");
        int index_BoundingBox_X = columns.FindIndex(x => x.Name == "BoundingBox X");
        int index_BoundingBox_Y = columns.FindIndex(x => x.Name == "BoundingBox Y");
        int index_BoundingBox_Width = columns.FindIndex(x => x.Name == "BoundingBox Width");
        int index_BoundingBox_Height = columns.FindIndex(x => x.Name == "BoundingBox Height");
        int index_Population_2008 = columns.FindIndex(x => x.Name == "Polpulation 2008");
        int index_Population_2009 = columns.FindIndex(x => x.Name == "Polpulation 2009");
        int index_Population_2010 = columns.FindIndex(x => x.Name == "Polpulation 2010");
        int index_Population_2011 = columns.FindIndex(x => x.Name == "Polpulation 2011");
        int index_Population_2012 = columns.FindIndex(x => x.Name == "Polpulation 2012");
        int index_Population_2013 = columns.FindIndex(x => x.Name == "Polpulation 2013");
        int index_Population_2014 = columns.FindIndex(x => x.Name == "Polpulation 2014");
        int index_Population_2015 = columns.FindIndex(x => x.Name == "Polpulation 2015");
        int index_Population_2016 = columns.FindIndex(x => x.Name == "Polpulation 2016");
        int index_Population_2017 = columns.FindIndex(x => x.Name == "Polpulation 2017");
        int index_Population_2018 = columns.FindIndex(x => x.Name == "Polpulation 2018");
        int index_Population_2019 = columns.FindIndex(x => x.Name == "Polpulation 2019");
        int index_Population_2020 = columns.FindIndex(x => x.Name == "Polpulation 2020");
        int index_Population_2021 = columns.FindIndex(x => x.Name == "Polpulation 2021");
        int index_Population_2022 = columns.FindIndex(x => x.Name == "Polpulation 2022");
        int index_Population_2023 = columns.FindIndex(x => x.Name == "Polpulation 2023");
        int index_Population_2024 = columns.FindIndex(x => x.Name == "Polpulation 2024");
        int index_Population_2025 = columns.FindIndex(x => x.Name == "Polpulation 2025");
        int index_PredictionConfidence_2008 = columns.FindIndex(x => x.Name == "Prediction Confidence 2008");
        int index_PredictionBoundingBox_X_2008 = columns.FindIndex(x => x.Name == "Prediction BoundingBox X 2008");
        int index_PredictionBoundingBox_Y_2008 = columns.FindIndex(x => x.Name == "Prediction BoundingBox Y 2008");
        int index_PredictionBoundingBox_Width_2008 = columns.FindIndex(x => x.Name == "Prediction BoundingBox Width 2008");
        int index_PredictionBoundingBox_Height_2008 = columns.FindIndex(x => x.Name == "Prediction BoundingBox Height 2008");
        int index_PredictionConfidence_2009 = columns.FindIndex(x => x.Name == "Prediction Confidence 2009");
        int index_PredictionBoundingBox_X_2009 = columns.FindIndex(x => x.Name == "Prediction BoundingBox X 2009");
        int index_PredictionBoundingBox_Y_2009 = columns.FindIndex(x => x.Name == "Prediction BoundingBox Y 2009");
        int index_PredictionBoundingBox_Width_2009 = columns.FindIndex(x => x.Name == "Prediction BoundingBox Width 2009");
        int index_PredictionBoundingBox_Height_2009 = columns.FindIndex(x => x.Name == "Prediction BoundingBox Height 2009");
        int index_PredictionConfidence_2010 = columns.FindIndex(x => x.Name == "Prediction Confidence 2010");
        int index_PredictionBoundingBox_X_2010 = columns.FindIndex(x => x.Name == "Prediction BoundingBox X 2010");
        int index_PredictionBoundingBox_Y_2010 = columns.FindIndex(x => x.Name == "Prediction BoundingBox Y 2010");
        int index_PredictionBoundingBox_Width_2010 = columns.FindIndex(x => x.Name == "Prediction BoundingBox Width 2010");
        int index_PredictionBoundingBox_Height_2010 = columns.FindIndex(x => x.Name == "Prediction BoundingBox Height 2010");
        int index_PredictionConfidence_2011 = columns.FindIndex(x => x.Name == "Prediction Confidence 2011");
        int index_PredictionBoundingBox_X_2011 = columns.FindIndex(x => x.Name == "Prediction BoundingBox X 2011");
        int index_PredictionBoundingBox_Y_2011 = columns.FindIndex(x => x.Name == "Prediction BoundingBox Y 2011");
        int index_PredictionBoundingBox_Width_2011 = columns.FindIndex(x => x.Name == "Prediction BoundingBox Width 2011");
        int index_PredictionBoundingBox_Height_2011 = columns.FindIndex(x => x.Name == "Prediction BoundingBox Height 2011");
        int index_PredictionConfidence_2012 = columns.FindIndex(x => x.Name == "Prediction Confidence 2012");
        int index_PredictionBoundingBox_X_2012 = columns.FindIndex(x => x.Name == "Prediction BoundingBox X 2012");
        int index_PredictionBoundingBox_Y_2012 = columns.FindIndex(x => x.Name == "Prediction BoundingBox Y 2012");
        int index_PredictionBoundingBox_Width_2012 = columns.FindIndex(x => x.Name == "Prediction BoundingBox Width 2012");
        int index_PredictionBoundingBox_Height_2012 = columns.FindIndex(x => x.Name == "Prediction BoundingBox Height 2012");
        int index_PredictionConfidence_2013 = columns.FindIndex(x => x.Name == "Prediction Confidence 2013");
        int index_PredictionBoundingBox_X_2013 = columns.FindIndex(x => x.Name == "Prediction BoundingBox X 2013");
        int index_PredictionBoundingBox_Y_2013 = columns.FindIndex(x => x.Name == "Prediction BoundingBox Y 2013");
        int index_PredictionBoundingBox_Width_2013 = columns.FindIndex(x => x.Name == "Prediction BoundingBox Width 2013");
        int index_PredictionBoundingBox_Height_2013 = columns.FindIndex(x => x.Name == "Prediction BoundingBox Height 2013");
        int index_PredictionConfidence_2014 = columns.FindIndex(x => x.Name == "Prediction Confidence 2014");
        int index_PredictionBoundingBox_X_2014 = columns.FindIndex(x => x.Name == "Prediction BoundingBox X 2014");
        int index_PredictionBoundingBox_Y_2014 = columns.FindIndex(x => x.Name == "Prediction BoundingBox Y 2014");
        int index_PredictionBoundingBox_Width_2014 = columns.FindIndex(x => x.Name == "Prediction BoundingBox Width 2014");
        int index_PredictionBoundingBox_Height_2014 = columns.FindIndex(x => x.Name == "Prediction BoundingBox Height 2014");
        int index_PredictionConfidence_2015 = columns.FindIndex(x => x.Name == "Prediction Confidence 2015");
        int index_PredictionBoundingBox_X_2015 = columns.FindIndex(x => x.Name == "Prediction BoundingBox X 2015");
        int index_PredictionBoundingBox_Y_2015 = columns.FindIndex(x => x.Name == "Prediction BoundingBox Y 2015");
        int index_PredictionBoundingBox_Width_2015 = columns.FindIndex(x => x.Name == "Prediction BoundingBox Width 2015");
        int index_PredictionBoundingBox_Height_2015 = columns.FindIndex(x => x.Name == "Prediction BoundingBox Height 2015");
        int index_PredictionConfidence_2016 = columns.FindIndex(x => x.Name == "Prediction Confidence 2016");
        int index_PredictionBoundingBox_X_2016 = columns.FindIndex(x => x.Name == "Prediction BoundingBox X 2016");
        int index_PredictionBoundingBox_Y_2016 = columns.FindIndex(x => x.Name == "Prediction BoundingBox Y 2016");
        int index_PredictionBoundingBox_Width_2016 = columns.FindIndex(x => x.Name == "Prediction BoundingBox Width 2016");
        int index_PredictionBoundingBox_Height_2016 = columns.FindIndex(x => x.Name == "Prediction BoundingBox Height 2016");
        int index_PredictionConfidence_2017 = columns.FindIndex(x => x.Name == "Prediction Confidence 2017");
        int index_PredictionBoundingBox_X_2017 = columns.FindIndex(x => x.Name == "Prediction BoundingBox X 2017");
        int index_PredictionBoundingBox_Y_2017 = columns.FindIndex(x => x.Name == "Prediction BoundingBox Y 2017");
        int index_PredictionBoundingBox_Width_2017 = columns.FindIndex(x => x.Name == "Prediction BoundingBox Width 2017");
        int index_PredictionBoundingBox_Height_2017 = columns.FindIndex(x => x.Name == "Prediction BoundingBox Height 2017");
        int index_PredictionConfidence_2018 = columns.FindIndex(x => x.Name == "Prediction Confidence 2018");
        int index_PredictionBoundingBox_X_2018 = columns.FindIndex(x => x.Name == "Prediction BoundingBox X 2018");
        int index_PredictionBoundingBox_Y_2018 = columns.FindIndex(x => x.Name == "Prediction BoundingBox Y 2018");
        int index_PredictionBoundingBox_Width_2018 = columns.FindIndex(x => x.Name == "Prediction BoundingBox Width 2018");
        int index_PredictionBoundingBox_Height_2018 = columns.FindIndex(x => x.Name == "Prediction BoundingBox Height 2018");
        int index_PredictionConfidence_2019 = columns.FindIndex(x => x.Name == "Prediction Confidence 2019");
        int index_PredictionBoundingBox_X_2019 = columns.FindIndex(x => x.Name == "Prediction BoundingBox X 2019");
        int index_PredictionBoundingBox_Y_2019 = columns.FindIndex(x => x.Name == "Prediction BoundingBox Y 2019");
        int index_PredictionBoundingBox_Width_2019 = columns.FindIndex(x => x.Name == "Prediction BoundingBox Width 2019");
        int index_PredictionBoundingBox_Height_2019 = columns.FindIndex(x => x.Name == "Prediction BoundingBox Height 2019");
        int index_PredictionConfidence_2020 = columns.FindIndex(x => x.Name == "Prediction Confidence 2020");
        int index_PredictionBoundingBox_X_2020 = columns.FindIndex(x => x.Name == "Prediction BoundingBox X 2020");
        int index_PredictionBoundingBox_Y_2020 = columns.FindIndex(x => x.Name == "Prediction BoundingBox Y 2020");
        int index_PredictionBoundingBox_Width_2020 = columns.FindIndex(x => x.Name == "Prediction BoundingBox Width 2020");
        int index_PredictionBoundingBox_Height_2020 = columns.FindIndex(x => x.Name == "Prediction BoundingBox Height 2020");
        int index_PredictionConfidence_2021 = columns.FindIndex(x => x.Name == "Prediction Confidence 2021");
        int index_PredictionBoundingBox_X_2021 = columns.FindIndex(x => x.Name == "Prediction BoundingBox X 2021");
        int index_PredictionBoundingBox_Y_2021 = columns.FindIndex(x => x.Name == "Prediction BoundingBox Y 2021");
        int index_PredictionBoundingBox_Width_2021 = columns.FindIndex(x => x.Name == "Prediction BoundingBox Width 2021");
        int index_PredictionBoundingBox_Height_2021 = columns.FindIndex(x => x.Name == "Prediction BoundingBox Height 2021");
        int index_PredictionConfidence_2022 = columns.FindIndex(x => x.Name == "Prediction Confidence 2022");
        int index_PredictionBoundingBox_X_2022 = columns.FindIndex(x => x.Name == "Prediction BoundingBox X 2022");
        int index_PredictionBoundingBox_Y_2022 = columns.FindIndex(x => x.Name == "Prediction BoundingBox Y 2022");
        int index_PredictionBoundingBox_Width_2022 = columns.FindIndex(x => x.Name == "Prediction BoundingBox Width 2022");
        int index_PredictionBoundingBox_Height_2022 = columns.FindIndex(x => x.Name == "Prediction BoundingBox Height 2022");
        int index_PredictionConfidence_2023 = columns.FindIndex(x => x.Name == "Prediction Confidence 2023");
        int index_PredictionBoundingBox_X_2023 = columns.FindIndex(x => x.Name == "Prediction BoundingBox X 2023");
        int index_PredictionBoundingBox_Y_2023 = columns.FindIndex(x => x.Name == "Prediction BoundingBox Y 2023");
        int index_PredictionBoundingBox_Width_2023 = columns.FindIndex(x => x.Name == "Prediction BoundingBox Width 2023");
        int index_PredictionBoundingBox_Height_2023 = columns.FindIndex(x => x.Name == "Prediction BoundingBox Height 2023");
        int index_PredictionConfidence_2024 = columns.FindIndex(x => x.Name == "Prediction Confidence 2024");
        int index_PredictionBoundingBox_X_2024 = columns.FindIndex(x => x.Name == "Prediction BoundingBox X 2024");
        int index_PredictionBoundingBox_Y_2024 = columns.FindIndex(x => x.Name == "Prediction BoundingBox Y 2024");
        int index_PredictionBoundingBox_Width_2024 = columns.FindIndex(x => x.Name == "Prediction BoundingBox Width 2024");
        int index_PredictionBoundingBox_Height_2024 = columns.FindIndex(x => x.Name == "Prediction BoundingBox Height 2024");
        int index_PredictionConfidence_2025 = columns.FindIndex(x => x.Name == "Prediction Confidence 2025");
        int index_PredictionBoundingBox_X_2025 = columns.FindIndex(x => x.Name == "Prediction BoundingBox X 2025");
        int index_PredictionBoundingBox_Y_2025 = columns.FindIndex(x => x.Name == "Prediction BoundingBox Y 2025");
        int index_PredictionBoundingBox_Width_2025 = columns.FindIndex(x => x.Name == "Prediction BoundingBox Width 2025");
        int index_PredictionBoundingBox_Height_2025 = columns.FindIndex(x => x.Name == "Prediction BoundingBox Height 2025");

        int index_YearBuilt = columns.FindIndex(x => x.Name == "Year Built");

        foreach (Row row in table.Rows)
        {
            string? reference = row.GetValue(index_Reference, string.Empty) ?? string.Empty;
            int yearBuilt = row.GetValue(index_YearBuilt, -1);

            OrtoBuildingDetectionModel.ModelInput modelInput = new()
            {
                Reference = reference,
                Building_General_Function = row.GetValue(index_BuildingGeneralFunction, -1F),
                Building_Phase = row.GetValue(index_BuildingPhase, -1F),
                Storeys = row.GetValue(index_Storeys, 0F),
                Area = row.GetValue(index_Area, 0F),
                Location_X = row.GetValue(index_Location_X, 0F),
                Location_Y = row.GetValue(index_Location_Y, 0F),
                Voivodeship = row.GetValue(index_Voivodeship, -1F),
                County = row.GetValue(index_County, -1F),
                Municipality = row.GetValue(index_Municipality, -1F),
                Subdivision = row.GetValue(index_Subdivision, -1F),
                Subdivision_Calculated_Occupancy = row.GetValue(index_SubdivisionCalculatedOccupancy, 0F),
                Subdivision_Calculated_Occupancy_Area = row.GetValue(index_SubdivisionCalculatedOccupancyArea, 0F),
                BoundingBox_X = row.GetValue(index_BoundingBox_X, 0F),
                BoundingBox_Y = row.GetValue(index_BoundingBox_Y, 0F),
                BoundingBox_Width = row.GetValue(index_BoundingBox_Width, 0F),
                BoundingBox_Height = row.GetValue(index_BoundingBox_Height, 0F),
                Polpulation_2008 = row.GetValue(index_Population_2008, 0F),
                Polpulation_2009 = row.GetValue(index_Population_2009, 0F),
                Polpulation_2010 = row.GetValue(index_Population_2010, 0F),
                Polpulation_2011 = row.GetValue(index_Population_2011, 0F),
                Polpulation_2012 = row.GetValue(index_Population_2012, 0F),
                Polpulation_2013 = row.GetValue(index_Population_2013, 0F),
                Polpulation_2014 = row.GetValue(index_Population_2014, 0F),
                Polpulation_2015 = row.GetValue(index_Population_2015, 0F),
                Polpulation_2016 = row.GetValue(index_Population_2016, 0F),
                Polpulation_2017 = row.GetValue(index_Population_2017, 0F),
                Polpulation_2018 = row.GetValue(index_Population_2018, 0F),
                Polpulation_2019 = row.GetValue(index_Population_2019, 0F),
                Polpulation_2020 = row.GetValue(index_Population_2020, 0F),
                Polpulation_2021 = row.GetValue(index_Population_2021, 0F),
                Polpulation_2022 = row.GetValue(index_Population_2022, 0F),
                Polpulation_2023 = row.GetValue(index_Population_2023, 0F),
                Polpulation_2024 = row.GetValue(index_Population_2024, 0F),
                Polpulation_2025 = row.GetValue(index_Population_2025, 0F),
                Prediction_Confidence_2008 = row.GetValue(index_PredictionConfidence_2008, 0F),
                Prediction_BoundingBox_X_2008 = row.GetValue(index_PredictionBoundingBox_X_2008, 0F),
                Prediction_BoundingBox_Y_2008 = row.GetValue(index_PredictionBoundingBox_Y_2008, 0F),
                Prediction_BoundingBox_Width_2008 = row.GetValue(index_PredictionBoundingBox_Width_2008, 0F),
                Prediction_BoundingBox_Height_2008 = row.GetValue(index_PredictionBoundingBox_Height_2008, 0F),
                Prediction_Confidence_2009 = row.GetValue(index_PredictionConfidence_2009, 0F),
                Prediction_BoundingBox_X_2009 = row.GetValue(index_PredictionBoundingBox_X_2009, 0F),
                Prediction_BoundingBox_Y_2009 = row.GetValue(index_PredictionBoundingBox_Y_2009, 0F),
                Prediction_BoundingBox_Width_2009 = row.GetValue(index_PredictionBoundingBox_Width_2009, 0F),
                Prediction_BoundingBox_Height_2009 = row.GetValue(index_PredictionBoundingBox_Height_2009, 0F),
                Prediction_Confidence_2010 = row.GetValue(index_PredictionConfidence_2010, 0F),
                Prediction_BoundingBox_X_2010 = row.GetValue(index_PredictionBoundingBox_X_2010, 0F),
                Prediction_BoundingBox_Y_2010 = row.GetValue(index_PredictionBoundingBox_Y_2010, 0F),
                Prediction_BoundingBox_Width_2010 = row.GetValue(index_PredictionBoundingBox_Width_2010, 0F),
                Prediction_BoundingBox_Height_2010 = row.GetValue(index_PredictionBoundingBox_Height_2010, 0F),
                Prediction_Confidence_2011 = row.GetValue(index_PredictionConfidence_2011, 0F),
                Prediction_BoundingBox_X_2011 = row.GetValue(index_PredictionBoundingBox_X_2011, 0F),
                Prediction_BoundingBox_Y_2011 = row.GetValue(index_PredictionBoundingBox_Y_2011, 0F),
                Prediction_BoundingBox_Width_2011 = row.GetValue(index_PredictionBoundingBox_Width_2011, 0F),
                Prediction_BoundingBox_Height_2011 = row.GetValue(index_PredictionBoundingBox_Height_2011, 0F),
                Prediction_Confidence_2012 = row.GetValue(index_PredictionConfidence_2012, 0F),
                Prediction_BoundingBox_X_2012 = row.GetValue(index_PredictionBoundingBox_X_2012, 0F),
                Prediction_BoundingBox_Y_2012 = row.GetValue(index_PredictionBoundingBox_Y_2012, 0F),
                Prediction_BoundingBox_Width_2012 = row.GetValue(index_PredictionBoundingBox_Width_2012, 0F),
                Prediction_BoundingBox_Height_2012 = row.GetValue(index_PredictionBoundingBox_Height_2012, 0F),
                Prediction_Confidence_2013 = row.GetValue(index_PredictionConfidence_2013, 0F),
                Prediction_BoundingBox_X_2013 = row.GetValue(index_PredictionBoundingBox_X_2013, 0F),
                Prediction_BoundingBox_Y_2013 = row.GetValue(index_PredictionBoundingBox_Y_2013, 0F),
                Prediction_BoundingBox_Width_2013 = row.GetValue(index_PredictionBoundingBox_Width_2013, 0F),
                Prediction_BoundingBox_Height_2013 = row.GetValue(index_PredictionBoundingBox_Height_2013, 0F),
                Prediction_Confidence_2014 = row.GetValue(index_PredictionConfidence_2014, 0F),
                Prediction_BoundingBox_X_2014 = row.GetValue(index_PredictionBoundingBox_X_2014, 0F),
                Prediction_BoundingBox_Y_2014 = row.GetValue(index_PredictionBoundingBox_Y_2014, 0F),
                Prediction_BoundingBox_Width_2014 = row.GetValue(index_PredictionBoundingBox_Width_2014, 0F),
                Prediction_BoundingBox_Height_2014 = row.GetValue(index_PredictionBoundingBox_Height_2014, 0F),
                Prediction_Confidence_2015 = row.GetValue(index_PredictionConfidence_2015, 0F),
                Prediction_BoundingBox_X_2015 = row.GetValue(index_PredictionBoundingBox_X_2015, 0F),
                Prediction_BoundingBox_Y_2015 = row.GetValue(index_PredictionBoundingBox_Y_2015, 0F),
                Prediction_BoundingBox_Width_2015 = row.GetValue(index_PredictionBoundingBox_Width_2015, 0F),
                Prediction_BoundingBox_Height_2015 = row.GetValue(index_PredictionBoundingBox_Height_2015, 0F),
                Prediction_Confidence_2016 = row.GetValue(index_PredictionConfidence_2016, 0F),
                Prediction_BoundingBox_X_2016 = row.GetValue(index_PredictionBoundingBox_X_2016, 0F),
                Prediction_BoundingBox_Y_2016 = row.GetValue(index_PredictionBoundingBox_Y_2016, 0F),
                Prediction_BoundingBox_Width_2016 = row.GetValue(index_PredictionBoundingBox_Width_2016, 0F),
                Prediction_BoundingBox_Height_2016 = row.GetValue(index_PredictionBoundingBox_Height_2016, 0F),
                Prediction_Confidence_2017 = row.GetValue(index_PredictionConfidence_2017, 0F),
                Prediction_BoundingBox_X_2017 = row.GetValue(index_PredictionBoundingBox_X_2017, 0F),
                Prediction_BoundingBox_Y_2017 = row.GetValue(index_PredictionBoundingBox_Y_2017, 0F),
                Prediction_BoundingBox_Width_2017 = row.GetValue(index_PredictionBoundingBox_Width_2017, 0F),
                Prediction_BoundingBox_Height_2017 = row.GetValue(index_PredictionBoundingBox_Height_2017, 0F),
                Prediction_Confidence_2018 = row.GetValue(index_PredictionConfidence_2018, 0F),
                Prediction_BoundingBox_X_2018 = row.GetValue(index_PredictionBoundingBox_X_2018, 0F),
                Prediction_BoundingBox_Y_2018 = row.GetValue(index_PredictionBoundingBox_Y_2018, 0F),
                Prediction_BoundingBox_Width_2018 = row.GetValue(index_PredictionBoundingBox_Width_2018, 0F),
                Prediction_BoundingBox_Height_2018 = row.GetValue(index_PredictionBoundingBox_Height_2018, 0F),
                Prediction_Confidence_2019 = row.GetValue(index_PredictionConfidence_2019, 0F),
                Prediction_BoundingBox_X_2019 = row.GetValue(index_PredictionBoundingBox_X_2019, 0F),
                Prediction_BoundingBox_Y_2019 = row.GetValue(index_PredictionBoundingBox_Y_2019, 0F),
                Prediction_BoundingBox_Width_2019 = row.GetValue(index_PredictionBoundingBox_Width_2019, 0F),
                Prediction_BoundingBox_Height_2019 = row.GetValue(index_PredictionBoundingBox_Height_2019, 0F),
                Prediction_Confidence_2020 = row.GetValue(index_PredictionConfidence_2020, 0F),
                Prediction_BoundingBox_X_2020 = row.GetValue(index_PredictionBoundingBox_X_2020, 0F),
                Prediction_BoundingBox_Y_2020 = row.GetValue(index_PredictionBoundingBox_Y_2020, 0F),
                Prediction_BoundingBox_Width_2020 = row.GetValue(index_PredictionBoundingBox_Width_2020, 0F),
                Prediction_BoundingBox_Height_2020 = row.GetValue(index_PredictionBoundingBox_Height_2020, 0F),
                Prediction_Confidence_2021 = row.GetValue(index_PredictionConfidence_2021, 0F),
                Prediction_BoundingBox_X_2021 = row.GetValue(index_PredictionBoundingBox_X_2021, 0F),
                Prediction_BoundingBox_Y_2021 = row.GetValue(index_PredictionBoundingBox_Y_2021, 0F),
                Prediction_BoundingBox_Width_2021 = row.GetValue(index_PredictionBoundingBox_Width_2021, 0F),
                Prediction_BoundingBox_Height_2021 = row.GetValue(index_PredictionBoundingBox_Height_2021, 0F),
                Prediction_Confidence_2022 = row.GetValue(index_PredictionConfidence_2022, 0F),
                Prediction_BoundingBox_X_2022 = row.GetValue(index_PredictionBoundingBox_X_2022, 0F),
                Prediction_BoundingBox_Y_2022 = row.GetValue(index_PredictionBoundingBox_Y_2022, 0F),
                Prediction_BoundingBox_Width_2022 = row.GetValue(index_PredictionBoundingBox_Width_2022, 0F),
                Prediction_BoundingBox_Height_2022 = row.GetValue(index_PredictionBoundingBox_Height_2022, 0F),
                Prediction_Confidence_2023 = row.GetValue(index_PredictionConfidence_2023, 0F),
                Prediction_BoundingBox_X_2023 = row.GetValue(index_PredictionBoundingBox_X_2023, 0F),
                Prediction_BoundingBox_Y_2023 = row.GetValue(index_PredictionBoundingBox_Y_2023, 0F),
                Prediction_BoundingBox_Width_2023 = row.GetValue(index_PredictionBoundingBox_Width_2023, 0F),
                Prediction_BoundingBox_Height_2023 = row.GetValue(index_PredictionBoundingBox_Height_2023, 0F),
                Prediction_Confidence_2024 = row.GetValue(index_PredictionConfidence_2024, 0F),
                Prediction_BoundingBox_X_2024 = row.GetValue(index_PredictionBoundingBox_X_2024, 0F),
                Prediction_BoundingBox_Y_2024 = row.GetValue(index_PredictionBoundingBox_Y_2024, 0F),
                Prediction_BoundingBox_Width_2024 = row.GetValue(index_PredictionBoundingBox_Width_2024, 0F),
                Prediction_BoundingBox_Height_2024 = row.GetValue(index_PredictionBoundingBox_Height_2024, 0F),
                Prediction_Confidence_2025 = row.GetValue(index_PredictionConfidence_2025, 0F),
                Prediction_BoundingBox_X_2025 = row.GetValue(index_PredictionBoundingBox_X_2025, 0F),
                Prediction_BoundingBox_Y_2025 = row.GetValue(index_PredictionBoundingBox_Y_2025, 0F),
                Prediction_BoundingBox_Width_2025 = row.GetValue(index_PredictionBoundingBox_Width_2025, 0F),
                Prediction_BoundingBox_Height_2025 = row.GetValue(index_PredictionBoundingBox_Height_2025, 0F),
            };

            var predictionResult = OrtoBuildingDetectionModel.Predict(modelInput);

            double value = predictionResult.Score;

            int floor = (int)Math.Floor(value);
            value = value - floor > 0.5 ? floor + 1 : floor;

            string line = string.Format("{0}\t{1}\n", reference, value);

            File.AppendAllText(path_Output, line);

            Console.WriteLine(line);
        }
    }
}

//string[] values = File.ReadAllLines(path);
//if(values != null)
//{
//    foreach(string value in values)
//    {
//    }
//}

Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

// Create single instance of sample data from first line of dataset for model input

//Console.WriteLine("Using model to make single prediction -- Comparing actual Year_Built with predicted Year_Built from sample data...\n\n");

//Console.WriteLine($"Reference: {@"272D6AAF-7D62-9B0E-E053-CC2BA8C0B5EA"}");
//Console.WriteLine($"Building_General_Function: {2F}");
//Console.WriteLine($"Building_Phase: {0F}");
//Console.WriteLine($"Storeys: {2F}");
//Console.WriteLine($"Area: {131.0792F}");
//Console.WriteLine($"Location_X: {252813.55F}");
//Console.WriteLine($"Location_Y: {369985.03F}");
//Console.WriteLine($"Voivodeship: {15567F}");
//Console.WriteLine($"County: {4774F}");
//Console.WriteLine($"Municipality: {56234F}");
//Console.WriteLine($"Subdivision: {22914F}");
//Console.WriteLine($"Subdivision_Calculated_Occupancy: {1473F}");
//Console.WriteLine($"Subdivision_Calculated_Occupancy_Area: {90240.48F}");
//Console.WriteLine($"BoundingBox_X: {252813.75F}");
//Console.WriteLine($"BoundingBox_Y: {369984.62F}");
//Console.WriteLine($"BoundingBox_Width: {18.78F}");
//Console.WriteLine($"BoundingBox_Height: {12.23F}");
//Console.WriteLine($"Polpulation_2008: {10800F}");
//Console.WriteLine($"Polpulation_2009: {10880F}");
//Console.WriteLine($"Polpulation_2010: {11010F}");
//Console.WriteLine($"Polpulation_2011: {11040F}");
//Console.WriteLine($"Polpulation_2012: {11050F}");
//Console.WriteLine($"Polpulation_2013: {11010F}");
//Console.WriteLine($"Polpulation_2014: {11020F}");
//Console.WriteLine($"Polpulation_2015: {11020F}");
//Console.WriteLine($"Polpulation_2016: {11070F}");
//Console.WriteLine($"Polpulation_2017: {11050F}");
//Console.WriteLine($"Polpulation_2018: {11020F}");
//Console.WriteLine($"Polpulation_2019: {11010F}");
//Console.WriteLine($"Polpulation_2020: {10690F}");
//Console.WriteLine($"Polpulation_2021: {10630F}");
//Console.WriteLine($"Polpulation_2022: {10560F}");
//Console.WriteLine($"Polpulation_2023: {10520F}");
//Console.WriteLine($"Polpulation_2024: {0F}");
//Console.WriteLine($"Polpulation_2025: {0F}");
//Console.WriteLine($"Prediction_Confidence_2008: {0.8489116F}");
//Console.WriteLine($"Prediction_BoundingBox_X_2008: {177.03554F}");
//Console.WriteLine($"Prediction_BoundingBox_Y_2008: {195.74039F}");
//Console.WriteLine($"Prediction_BoundingBox_Width_2008: {274.61172F}");
//Console.WriteLine($"Prediction_BoundingBox_Height_2008: {246.22748F}");
//Console.WriteLine($"Prediction_Confidence_2009: {0.8111542F}");
//Console.WriteLine($"Prediction_BoundingBox_X_2009: {180.44846F}");
//Console.WriteLine($"Prediction_BoundingBox_Y_2009: {184.00372F}");
//Console.WriteLine($"Prediction_BoundingBox_Width_2009: {276.8252F}");
//Console.WriteLine($"Prediction_BoundingBox_Height_2009: {238.10931F}");
//Console.WriteLine($"Prediction_Confidence_2010: {0.8111542F}");
//Console.WriteLine($"Prediction_BoundingBox_X_2010: {180.44846F}");
//Console.WriteLine($"Prediction_BoundingBox_Y_2010: {184.00372F}");
//Console.WriteLine($"Prediction_BoundingBox_Width_2010: {276.8252F}");
//Console.WriteLine($"Prediction_BoundingBox_Height_2010: {238.10931F}");
//Console.WriteLine($"Prediction_Confidence_2011: {0.8111542F}");
//Console.WriteLine($"Prediction_BoundingBox_X_2011: {180.44846F}");
//Console.WriteLine($"Prediction_BoundingBox_Y_2011: {184.00372F}");
//Console.WriteLine($"Prediction_BoundingBox_Width_2011: {276.8252F}");
//Console.WriteLine($"Prediction_BoundingBox_Height_2011: {238.10931F}");
//Console.WriteLine($"Prediction_Confidence_2012: {0.8111542F}");
//Console.WriteLine($"Prediction_BoundingBox_X_2012: {180.44846F}");
//Console.WriteLine($"Prediction_BoundingBox_Y_2012: {184.00372F}");
//Console.WriteLine($"Prediction_BoundingBox_Width_2012: {276.8252F}");
//Console.WriteLine($"Prediction_BoundingBox_Height_2012: {238.10931F}");
//Console.WriteLine($"Prediction_Confidence_2013: {0.8624096F}");
//Console.WriteLine($"Prediction_BoundingBox_X_2013: {184.65092F}");
//Console.WriteLine($"Prediction_BoundingBox_Y_2013: {194.2467F}");
//Console.WriteLine($"Prediction_BoundingBox_Width_2013: {279.71878F}");
//Console.WriteLine($"Prediction_BoundingBox_Height_2013: {236.88264F}");
//Console.WriteLine($"Prediction_Confidence_2014: {0.8624096F}");
//Console.WriteLine($"Prediction_BoundingBox_X_2014: {184.65092F}");
//Console.WriteLine($"Prediction_BoundingBox_Y_2014: {194.2467F}");
//Console.WriteLine($"Prediction_BoundingBox_Width_2014: {279.71878F}");
//Console.WriteLine($"Prediction_BoundingBox_Height_2014: {236.88264F}");
//Console.WriteLine($"Prediction_Confidence_2015: {0.85267836F}");
//Console.WriteLine($"Prediction_BoundingBox_X_2015: {178.35895F}");
//Console.WriteLine($"Prediction_BoundingBox_Y_2015: {198.89273F}");
//Console.WriteLine($"Prediction_BoundingBox_Width_2015: {272.81854F}");
//Console.WriteLine($"Prediction_BoundingBox_Height_2015: {245.71863F}");
//Console.WriteLine($"Prediction_Confidence_2016: {0.85267836F}");
//Console.WriteLine($"Prediction_BoundingBox_X_2016: {178.35895F}");
//Console.WriteLine($"Prediction_BoundingBox_Y_2016: {198.89273F}");
//Console.WriteLine($"Prediction_BoundingBox_Width_2016: {272.81854F}");
//Console.WriteLine($"Prediction_BoundingBox_Height_2016: {245.71863F}");
//Console.WriteLine($"Prediction_Confidence_2017: {0.85964555F}");
//Console.WriteLine($"Prediction_BoundingBox_X_2017: {181.25626F}");
//Console.WriteLine($"Prediction_BoundingBox_Y_2017: {197.50197F}");
//Console.WriteLine($"Prediction_BoundingBox_Width_2017: {275.53717F}");
//Console.WriteLine($"Prediction_BoundingBox_Height_2017: {238.82632F}");
//Console.WriteLine($"Prediction_Confidence_2018: {0.85964555F}");
//Console.WriteLine($"Prediction_BoundingBox_X_2018: {181.25626F}");
//Console.WriteLine($"Prediction_BoundingBox_Y_2018: {197.50197F}");
//Console.WriteLine($"Prediction_BoundingBox_Width_2018: {275.53717F}");
//Console.WriteLine($"Prediction_BoundingBox_Height_2018: {238.82632F}");
//Console.WriteLine($"Prediction_Confidence_2019: {0.85310423F}");
//Console.WriteLine($"Prediction_BoundingBox_X_2019: {180.96625F}");
//Console.WriteLine($"Prediction_BoundingBox_Y_2019: {201.96324F}");
//Console.WriteLine($"Prediction_BoundingBox_Width_2019: {274.8075F}");
//Console.WriteLine($"Prediction_BoundingBox_Height_2019: {245.35385F}");
//Console.WriteLine($"Prediction_Confidence_2020: {0.861835F}");
//Console.WriteLine($"Prediction_BoundingBox_X_2020: {181.28354F}");
//Console.WriteLine($"Prediction_BoundingBox_Y_2020: {197.70544F}");
//Console.WriteLine($"Prediction_BoundingBox_Width_2020: {280.84467F}");
//Console.WriteLine($"Prediction_BoundingBox_Height_2020: {240.21533F}");
//Console.WriteLine($"Prediction_Confidence_2021: {0.84820616F}");
//Console.WriteLine($"Prediction_BoundingBox_X_2021: {180.70023F}");
//Console.WriteLine($"Prediction_BoundingBox_Y_2021: {193.75652F}");
//Console.WriteLine($"Prediction_BoundingBox_Width_2021: {271.85654F}");
//Console.WriteLine($"Prediction_BoundingBox_Height_2021: {237.0311F}");
//Console.WriteLine($"Prediction_Confidence_2022: {0.84820616F}");
//Console.WriteLine($"Prediction_BoundingBox_X_2022: {180.70023F}");
//Console.WriteLine($"Prediction_BoundingBox_Y_2022: {193.75652F}");
//Console.WriteLine($"Prediction_BoundingBox_Width_2022: {271.85654F}");
//Console.WriteLine($"Prediction_BoundingBox_Height_2022: {237.0311F}");
//Console.WriteLine($"Prediction_Confidence_2023: {0.86356944F}");
//Console.WriteLine($"Prediction_BoundingBox_X_2023: {179.53168F}");
//Console.WriteLine($"Prediction_BoundingBox_Y_2023: {202.81845F}");
//Console.WriteLine($"Prediction_BoundingBox_Width_2023: {274.9209F}");
//Console.WriteLine($"Prediction_BoundingBox_Height_2023: {243.94556F}");
//Console.WriteLine($"Prediction_Confidence_2024: {0.86356944F}");
//Console.WriteLine($"Prediction_BoundingBox_X_2024: {179.53168F}");
//Console.WriteLine($"Prediction_BoundingBox_Y_2024: {202.81845F}");
//Console.WriteLine($"Prediction_BoundingBox_Width_2024: {274.9209F}");
//Console.WriteLine($"Prediction_BoundingBox_Height_2024: {243.94556F}");
//Console.WriteLine($"Prediction_Confidence_2025: {0.86356944F}");
//Console.WriteLine($"Prediction_BoundingBox_X_2025: {179.53168F}");
//Console.WriteLine($"Prediction_BoundingBox_Y_2025: {202.81845F}");
//Console.WriteLine($"Prediction_BoundingBox_Width_2025: {274.9209F}");
//Console.WriteLine($"Prediction_BoundingBox_Height_2025: {243.94556F}");
//Console.WriteLine($"Year_Built: {2008F}");

// Make a single prediction on the sample data and print results

//Console.WriteLine("=============== End of process, hit any key to finish ===============");
//Console.ReadKey();